'use strict';
// English AI Teacher v1.0 - iPhone PWA - Author: Ali Erkonak
const STORAGE_KEY='english_ai_teacher_iphone_v1';
const root=document.getElementById('view');
const TODAY=()=>new Date().toLocaleDateString('en-CA');
const defaultState=()=>({completed:{},attempts:0,correct:0,misses:{},days:[],chat:[],settings:{ai:'offline',worker:'',token:'',autoplay:false,voiceRate:0.87},created:Date.now()});
let state=loadState(),page='home',quiz=null,speakIndex=0,recorder=null,hearing=false,heard='',speakFeedback='',engine=null,engineLoading=false,engineMessage='',isSending=false,toastTimer=null;
function loadState(){try{let s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s&&typeof s==='object')return {...defaultState(),...s,settings:{...defaultState().settings,...(s.settings||{})}};}catch(e){}return defaultState();}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){toast('Kayıt yapılamadı. Safari depolama alanını kontrol et.')}}
function h(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function clean(s){return String(s||'').normalize('NFKC').toLowerCase().replace(/[’‘`]/g,"'").replace(/[.,!?;:]+/g,'').replace(/\s+/g,' ').trim();}
function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000);}
function answered(q,a){return q.answers.some(x=>clean(x)===clean(a));}
function completedCount(){return LESSONS.filter(l=>state.completed[l.id]?.score>=75).length;}
function nextLesson(){return LESSONS.find(l=>!state.completed[l.id]||state.completed[l.id].score<75)||LESSONS[LESSONS.length-1];}
function lessonUnlocked(idx){return idx===0||LESSONS.slice(0,idx).every(l=>state.completed[l.id]?.score>=75);}
function currentLesson(){let l=nextLesson();return l||LESSONS[0];}
function activity(){let d=TODAY();if(!state.days.includes(d)){state.days.push(d);state.days=state.days.slice(-400);}save()}
function streak(){let n=0,all=new Set(state.days);let d=new Date();if(!all.has(TODAY()))d.setDate(d.getDate()-1);for(let i=0;i<365;i++){let x=d.toLocaleDateString('en-CA');if(!all.has(x))break;n++;d.setDate(d.getDate()-1);}return n}
function render(){document.querySelectorAll('.navitem').forEach(x=>x.classList.toggle('active',x.dataset.page===page));if(page==='home')renderHome();else if(page==='courses')renderCourses();else if(page==='lesson')renderLesson();else if(page==='quiz')renderQuiz();else if(page==='speaking')renderSpeaking();else if(page==='chat')renderChat();else if(page==='stats')renderStats();else if(page==='settings')renderSettings();}
function go(next){if(recorder&&hearing){try{recorder.abort()}catch(e){}hearing=false;}page=next;render();window.scrollTo(0,0)}
function cap(l){return `${h(l.id)} · ${h(l.level)}`}
function renderHome(){let l=currentLesson(),cnt=completedCount(),progress=Math.round(cnt/LESSONS.length*100),due=dueQuestions().length;
root.innerHTML=`<div class="hero"><span class="chip">✦ Kişisel İngilizce eğitmenin</span><h1>Bugün bir adım daha ileri.</h1><p>Hazır olduğunda öğretmenin kaldığın yerden devam edecek.</p><button class="btn" data-action="continue">Derse devam et →</button></div>
<div class="grid2"><div class="kpi"><small>Seviye</small><span class="num">${h(l.level)}</span><small>Sıradaki dersin</small></div><div class="kpi"><small>Günlük seri</small><span class="num">${streak()} gün</span><small>İstikrarlı pratik</small></div></div>
<h2 class="section-title">Öğretmenin bugün öneriyor</h2><section class="card"><div class="row between"><span class="badge">${cap(l)}</span><small class="muted">${cnt}/${LESSONS.length} ders</small></div><h3>${h(l.title)}</h3><p class="muted">${h(l.tr)}</p><div class="progress" aria-label="İlerleme"><div style="width:${progress}%"></div></div><p class="tiny">Müfredat ilerlemesi: %${progress}</p><button class="btn full" data-action="continue">${cnt===LESSONS.length?'Tekrar et':'Dersi aç'} →</button></section>
<div class="grid2"><button class="lessonitem" data-page="speaking"><span class="lessonnum">♫</span><span><strong>Sesli pratik</strong><small>Dinle ve konuş</small></span></button><button class="lessonitem" data-page="chat"><span class="lessonnum">✦</span><span><strong>AI öğretmen</strong><small>Serbest sohbet</small></span></button></div>
${due?`<div class="card"><strong>🔁 ${due} tekrar sorusu var</strong><p class="muted">Yanlış yaptığın soruları yeniden çöz.</p><button class="btn secondary full" data-action="review">Yanlışlarımı çalış</button></div>`:''}
<div class="foot">English AI Teacher v1.0 · Developer: Ali Erkonak</div>`;}
function renderCourses(){let n=completedCount();root.innerHTML=`<div class="eyebrow">Ders programı</div><h1>Derslerim</h1><p class="muted">Öğretmenin sırayı belirler. Bir sonraki bölüme geçmek için önceki dersi en az %75 başarıyla tamamla.</p><div class="progress"><div style="width:${Math.round(n/LESSONS.length*100)}%"></div></div>${['A0','A1','A2'].map(level=>`<div class="divider-heading">${level} · ${level==='A0'?'Başlangıç':level==='A1'?'Temel İngilizce':'Ön orta seviye'}</div>${LESSONS.map((l,i)=>l.level!==level?'':`<button class="lessonitem" data-action="open-lesson" data-index="${i}" ${lessonUnlocked(i)?'':'disabled'}><span class="lessonnum">${state.completed[l.id]?.score>=75?'✓':lessonUnlocked(i)?i+1:'🔒'}</span><span><strong>${h(l.title)}</strong><small>${h(l.tr)}${state.completed[l.id]?' · Son skor: %'+state.completed[l.id].score:''}</small></span><span class="arrow">›</span></button>`).join('')}`).join('')}
<div class="card"><h3>Sonraki aşamalar: B1 → B2 → C1</h3><p class="muted">İleri seviyeler yol haritasında. Bu pakette yalnızca içerikleri hazırlanmış 24 ders açılmıştır; henüz hazır olmayan dersler tamamlanmış gibi gösterilmez.</p></div>`;}
function renderLesson(){let l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();root.innerHTML=`<button class="btn ghost" data-page="courses">← Derslere dön</button><div style="height:18px"></div><span class="badge">${cap(l)}</span><h1>${h(l.title)}</h1><p class="muted">${h(l.tr)}</p><h2 class="section-title">Öğretmenin anlatıyor</h2><div class="note">${h(l.rule)}</div><h2 class="section-title">Dinle ve tekrar et</h2><div class="card">${l.examples.map((x,i)=>`<div class="eg"><span style="flex:1">${h(x)}</span><button class="speakbtn" data-action="speak" data-text="${h(x)}" aria-label="Cümleyi dinle">▶</button></div>`).join('')}</div><p class="muted">Konu anlatımını çalıştıktan sonra mini sınava gir. %75 ve üzeri sonraki dersi açar.</p><button class="btn full" data-action="start-lesson-quiz">${state.completed[l.id]?'Sınavı tekrar çöz':'Mini sınava başla'} →</button>`;}
function startLessonQuiz(){let l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();quiz={kind:'lesson',lesson:l,questions:l.questions.map((q,i)=>({...q,key:l.id+'-'+i})),index:0,score:0,wrong:0,selected:'',submitted:false,lastCorrect:false};go('quiz')}
function dueQuestions(){let arr=[];for(let l of LESSONS){l.questions.forEach((q,i)=>{let key=l.id+'-'+i,m=state.misses[key];if(m&&(!m.due||m.due<=Date.now()))arr.push({...q,key,lessonId:l.id});});}return arr;}
function reviewQuiz(){let arr=dueQuestions();if(!arr.length){toast('Şu anda tekrarlanacak soru yok.');return;}quiz={kind:'review',lesson:null,questions:arr.sort((a,b)=>(state.misses[a.key]?.due||0)-(state.misses[b.key]?.due||0)).slice(0,20),index:0,score:0,wrong:0,selected:'',submitted:false,lastCorrect:false};go('quiz')}
function renderQuiz(){if(!quiz){go('home');return;}if(quiz.index>=quiz.questions.length){renderQuizResult();return;}let q=quiz.questions[quiz.index],num=quiz.index+1,perc=Math.round((num-1)/quiz.questions.length*100);root.innerHTML=`<div class="row between"><span class="badge">${quiz.kind==='review'?'Tekrar antrenmanı':cap(quiz.lesson)}</span><span class="muted">Soru ${num}/${quiz.questions.length}</span></div><div style="height:12px"></div><div class="progress"><div style="width:${perc}%"></div></div><h2 class="section-title" style="font-size:23px;margin-top:32px">${h(q.q)}</h2><p class="muted">${q.type==='choice'?'Bir cevabı seç.':q.type==='fill'?'Boşluğa gelen kelimeyi yaz.':'Cümleyi İngilizce olarak yaz.'}</p><div>${q.options.length?q.options.map((o,i)=>`<button class="option ${quiz.selected===o?'selected':''}${quiz.submitted?(answered(q,o)?' right':quiz.selected===o?' wrong':''):''}" data-action="choose" data-index="${i}" ${quiz.submitted?'disabled':''}>${h(o)}</button>`).join(''):`<input id="written-answer" class="field" placeholder="Cevabını yaz..." value="${h(quiz.selected)}" ${quiz.submitted?'readonly':''} autocomplete="off" autocapitalize="sentences" spellcheck="false">`}</div>
${quiz.submitted?`<div class="feedback ${quiz.lastCorrect?'':'bad'}"><strong>${quiz.lastCorrect?'✓ Doğru!':'✕ Tekrar çalışacağız'}</strong><div>${h(q.why)}</div>${quiz.lastCorrect?'':`<div style="margin-top:7px">Doğru cevap: <strong>${h(q.answers[0])}</strong></div>`}</div><button class="btn full" data-action="next-question">${num===quiz.questions.length?'Sonucu göster':'Sıradaki soru'} →</button>`:`<div style="height:18px"></div><button class="btn full" data-action="submit-answer">Cevabı kontrol et</button>`}`;
if(q.options.length===0&&!quiz.submitted){let inp=document.getElementById('written-answer');inp.addEventListener('input',e=>quiz.selected=e.target.value);inp.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();submitAnswer()}});}}
function submitAnswer(){if(!quiz||quiz.submitted)return;if(!clean(quiz.selected)){toast('Önce bir cevap gir.');return;}let q=quiz.questions[quiz.index],correct=answered(q,quiz.selected);quiz.lastCorrect=correct;quiz.submitted=true;state.attempts++;if(correct){state.correct++;quiz.score++}else quiz.wrong++;
let miss=state.misses[q.key];if(!correct){state.misses[q.key]={interval:0,due:Date.now(),errors:(miss?.errors||0)+1,title:q.q,answer:q.answers[0]}}else if(miss){let interval=Math.min(60,Math.max(1,(miss.interval||0)*2));state.misses[q.key]={...miss,interval,due:Date.now()+interval*86400000,corrected:Date.now()};}
activity();save();renderQuiz();}
function nextQuestion(){if(!quiz)return;quiz.index++;quiz.selected='';quiz.submitted=false;renderQuiz()}
function renderQuizResult(){const score=Math.round(quiz.score/quiz.questions.length*100),passed=score>=75;let name=quiz.kind==='lesson'?quiz.lesson.title:'Tekrar';if(quiz.kind==='lesson'){let old=state.completed[quiz.lesson.id];if(!old||old.score<score)state.completed[quiz.lesson.id]={score,ts:Date.now()};activity()}
root.innerHTML=`<div class="hero center"><div class="eyebrow">${h(name)}</div><h1 style="max-width:none">${score>=75?'Harika ilerleme!':'Biraz daha pratik!'}</h1><div style="font-size:60px;font-weight:850;color:var(--cyan)">%${score}</div><p style="max-width:none">${quiz.score} doğru · ${quiz.wrong} yanlış</p></div>${quiz.kind==='lesson'&&!passed?'<div class="warning">Sonraki ders için %75 gerekiyor. Öğretmenin bu konuyu yeniden çalışmanı öneriyor.</div>':''}<div class="grid2"><button class="btn secondary" data-action="repeat-quiz">Tekrar çöz</button><button class="btn" data-action="finish-quiz">${passed?'Devam et':'Derse dön'} →</button></div>`;save()}
function renderSpeaking(){let l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();let examples=l.examples||[],phrase=examples[speakIndex%examples.length];root.innerHTML=`<div class="eyebrow">Speaking studio</div><h1>Konuşma pratiği</h1><p class="muted">Cümleyi dinle, ardından İngilizce söyle. Ses tanıma cihazında desteklenmiyorsa klavyedeki dikte mikrofonunu kullanabilirsin.</p><div class="card center"><span class="badge">${cap(l)} · ${speakIndex%examples.length+1}/${examples.length}</span><h2 style="margin:25px 0 12px;font-size:23px">${h(phrase)}</h2><button class="btn secondary" data-action="play-phrase">▶ Öğretmeni dinle</button><div><button class="record ${hearing?'active':''}" data-action="record" aria-label="Konuşmayı başlat veya durdur">${hearing?'■':'🎙'}</button></div><p class="muted">${hearing?'Dinliyorum...':'Mikrofona dokun ve konuş'}</p></div><label class="label" for="heard">Algılanan cümle / klavye ile dikte</label><input id="heard" class="field" placeholder="Konuş veya cümleyi yaz" value="${h(heard)}" autocomplete="off"/><div style="height:12px"></div><button class="btn full" data-action="check-speak">Cümleyi karşılaştır</button>${speakFeedback?`<div class="feedback">${h(speakFeedback)}</div>`:''}<div style="height:14px"></div><button class="btn secondary full" data-action="next-phrase">Sonraki cümle →</button><div class="warning"><strong>Not:</strong> Bu ekran söylenen kelimeleri metinle karşılaştırır; profesyonel fonetik/telaffuz puanı vermez. iOS ana ekran uygulamalarında tarayıcı konuşma tanıma desteği değişebilir.</div>`;
let el=document.getElementById('heard');el.addEventListener('input',e=>heard=e.target.value);}
function voiceFor(lang){if(!('speechSynthesis'in window))return null;let a=speechSynthesis.getVoices(),v=a.filter(x=>x.lang.toLowerCase().startsWith(lang));return v.find(x=>/Samantha|Ava|Karen|Victoria|Zira|Jenny|Siri|female/i.test(x.name))||v[0]||null;}
function say(s,lang='en'){if(!('speechSynthesis'in window)){toast('Bu cihazda ses sentezi kullanılamıyor.');return;}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(s);u.lang=lang==='en'?'en-US':'tr-TR';u.rate=Number(state.settings.voiceRate)||.87;let v=voiceFor(lang);if(v)u.voice=v;speechSynthesis.speak(u);}
function startRecording(){if(hearing){try{recorder?.stop()}catch(e){}return;}let Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec){toast('Ses tanıma burada desteklenmiyor; iPhone klavyesinin diktesini kullan.');return;}try{recorder=new Rec();recorder.lang='en-US';recorder.interimResults=false;recorder.continuous=false;recorder.onresult=e=>{heard=Array.from(e.results).map(r=>r[0].transcript).join(' ');hearing=false;renderSpeaking()};recorder.onerror=e=>{hearing=false;toast('Ses tanıma hatası: '+e.error+'. Klavye diktesini dene.');renderSpeaking()};recorder.onend=()=>{hearing=false;if(page==='speaking')renderSpeaking()};recorder.start();hearing=true;renderSpeaking();}catch(e){hearing=false;toast('Mikrofon açılamadı. Dikteyi kullan.');}}
function checkSpeaking(){let l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson(),ref=l.examples[speakIndex%l.examples.length],a=clean(heard),b=clean(ref);if(!a){toast('Önce konuş veya bir cümle yaz.');return;}let r=new Set(b.split(' ')),s=new Set(a.split(' ')),hits=[...r].filter(x=>s.has(x)).length,ratio=Math.round(100*hits/Math.max(r.size,s.size));speakFeedback=ratio>=95?'Tüm kelimeler eşleşiyor. Güzel!':ratio>=65?`Kelime eşleşmesi yaklaşık %${ratio}. Öğretmenin cümlesini yeniden dinle ve tekrar et.`:`Kelime eşleşmesi yaklaşık %${ratio}. Örnek: ${ref}`;activity();renderSpeaking();}
function chatModes(){let ai=state.settings.ai;return ai==='device'?'iPhone üzerinde AI (deneysel)':ai==='cloud'?'Çevrimiçi gerçek AI':'Çevrimdışı hazır koç';}
function renderChat(){root.innerHTML=`<div class="eyebrow">Personal AI coach</div><h1>AI Öğretmen</h1><div class="row between"><span class="badge">${h(chatModes())}</span><button class="btn ghost" data-page="settings" style="min-height:35px;padding:7px 11px">Ayarla</button></div>
${state.settings.ai==='offline'?'<div class="warning">Bu mod gerçek üretken AI değildir. Önceden hazırlanmış kurallarla kısa geri bildirim verir. Serbest AI sohbeti için Ayarlar’dan iPhone AI veya güvenli sunucu modunu seç.</div>':''}
${state.settings.ai==='device'?`<div class="card"><strong>Yerel AI ${engine?'hazır':engineLoading?'yükleniyor':'henüz başlatılmadı'}</strong><p class="muted">${h(engineMessage||'İlk kullanımda yüzlerce MB model indirilir. Safari bellek hatası verebilir. İnternet ve yeterli depolama gerekir.')}</p><button class="btn secondary full" data-action="start-device" ${engineLoading||engine?'disabled':''}>${engine?'Model hazır':engineLoading?'Yükleniyor...':'Cihaz AI modelini yükle'}</button></div>`:''}
${state.settings.ai==='cloud'&&!state.settings.worker?'<div class="warning">Gerçek AI için Ayarlar’dan güvenli Worker adresini tanımlaman gerekiyor. Uygulama içerisinde API anahtarı bulundurulmaz.</div>':''}
<div class="chatbox" id="chatbox">${state.chat.length?state.chat.slice(-35).map(m=>`<div class="bubble ${m.role==='user'?'user':'assistant'}">${h(m.content)}</div>`).join(''):`<div class="bubble assistant">Hello! 👋 I’m your English practice partner. Try: “I’m learning English now.” Türkçe de yazabilirsin. ${state.settings.ai==='offline'?'Bu modda sadece hazır koç cevapları vardır.':''}</div>`}</div>
<div class="composer"><textarea id="chat-input" class="field" placeholder="Write a message…" rows="2" maxlength="1200" aria-label="AI öğretmene mesaj"></textarea><button class="btn" data-action="send" ${isSending?'disabled':''}>${isSending?'…':'Gönder'}</button></div><p class="tiny">AI cevapları hatalı olabilir. Ders içeriği ve gerçek AI konuşmaları ayrı tutulur.</p>`;
let box=document.getElementById('chatbox');box.scrollTop=box.scrollHeight;}
function knownOfflineCoach(s){let x=clean(s);const known=[
[/\bi am work(?!ing)\b/,"‘I am work’ yerine **I am working** (şu anda) veya **I work** (genel alışkanlık) yaz. Example: I am working now."],
[/\bi am study\b/,"Güzel deneme! ‘I am study’ yerine **I study English every day** veya **I am studying English now** yaz."],
[/\bi am usually\b/,"Usually rutin gösterir. **I usually get up at 9 o’clock.** (I am usually get up değil.)"],
[/\bi go to home\b/,"‘Go to home’ değil, **go home** kullanılır. Example: I am going home."],
[/\bi can (swimming|speaking|working)\b/,"Can'den sonra yalın fiil gerekir: **I can swim / I can speak / I can work.**"],
[/\beveryday\b/,"Zaman zarfı olarak **every day** (iki kelime). ‘Everyday’ ise sıfattır."],
[/\bstaying at hotel\b/,"Doğal kullanım: **I am staying at a hotel.** (a hotel)"],
[/\bgut up\b/,"Fiil **get up** olmalı: **I usually get up at nine.**"],
[/\bi am from turkey\b/,"Great! ✅ **I am from Turkey.** Şimdi şunu dene: ‘I live in Istanbul.’"],
[/\bi am learning english\b/,"Great! ✅ **I am learning English.** Şimdiki zaman doğru. Şimdi ‘I study English every day’ yazmayı dene."],
[/\bi work every day\b/,"Great! ✅ **I work every day.** Rutin için Present Simple doğru. Şimdi ‘I am working now’ dene."],
[/\b(hello|hi)\b/,"Hello! 👋 How are you today? Try answering with a complete sentence: ‘I’m fine, thank you.’"],
[/\bhow are you\b/,"I'm doing well, thank you! Now tell me: **What do you do every day?**"],
[/\b(merhaba|selam)\b/,"Hello! 👋 Bugün ‘I am...’ yapısını çalışalım. Bana İngilizce olarak nereli olduğunu söyle."],
];for(let [re,msg] of known)if(re.test(x))return msg.replace(/\*\*/g,'');let l=currentLesson();return `Çevrimdışı koç şu anda sınırlı cümleleri kontrol edebiliyor.\n\nBugünkü konun: ${l.title}\n${l.rule}\n\nÖrnek: ${l.examples[0]}\n\nSerbest cevap ve ayrıntılı düzeltme için Ayarlar > Gerçek AI modunu kullan.`;}
function systemPrompt(){let l=currentLesson(),miss=Object.values(state.misses).sort((a,b)=>b.errors-a.errors).slice(0,6).map(m=>`${m.title} => ${m.answer}`).join(' | ');return `You are an expert private English tutor for a Turkish A0-A2 learner. You own the curriculum; choose the next exercise. Current lesson: ${l.level} ${l.title}. Grammar: ${l.rule}. Important earlier mistakes: ${miss||'none yet'}. Be patient but precise, supportive not flattering. Keep answers short, maximum 120 words. Teach in Turkish for grammar explanations; English for practice, gradually increase English. For each learner response: 1) correct concrete mistakes and give the improved sentence, 2) briefly explain why in Turkish, 3) ask ONE useful follow-up question in English. If correct say so accurately. Never falsely claim to have heard or rated pronunciation. Prefer realistic conversation, travel/work/gym topics. No request for private data or payment.`}
async function loadDeviceModel(){if(engine||engineLoading){return;}if(!navigator.gpu){engineMessage='Bu Safari sürümünde WebGPU kullanılamıyor.';renderChat();return;}engineLoading=true;engineMessage='WebLLM modülü alınıyor…';renderChat();try{let lib=await import('https://esm.sh/@mlc-ai/web-llm@0.2.81?bundle');if(!lib.CreateMLCEngine)throw Error('WebLLM yüklenemedi');engine=await lib.CreateMLCEngine('SmolLM2-360M-Instruct-q4f16_1-MLC',{initProgressCallback:p=>{engineMessage=p.text||('Model indiriliyor: %'+Math.round(p.progress*100));if(page==='chat')renderChat();}});engineMessage='Yerel AI hazır. Bu küçük model hatalı cevaplar verebilir.';}catch(e){engine=null;engineMessage='Model yüklenemedi: '+String(e.message||e).slice(0,160)+' — Çevrimiçi AI seçeneğini deneyebilirsin.';}finally{engineLoading=false;if(page==='chat')renderChat();}}
async function sendChat(){if(isSending)return;let input=document.getElementById('chat-input');let val=input?.value.trim();if(!val)return;isSending=true;state.chat.push({role:'user',content:val.slice(0,1200)});state.chat=state.chat.slice(-70);save();renderChat();try{let answer;if(state.settings.ai==='offline'){answer=knownOfflineCoach(val);}else if(state.settings.ai==='device'){if(!engine)throw Error('Önce cihaz AI modelini başlat.');let messages=[{role:'system',content:systemPrompt()},...state.chat.slice(-10)];let result=await engine.chat.completions.create({messages,temperature:.65,max_tokens:260});answer=result.choices?.[0]?.message?.content||'Yanıt alınamadı.';}else if(state.settings.ai==='cloud'){
let base=String(state.settings.worker||'').trim();if(!/^https:\/\/[a-z0-9.-]+(?:\/[a-z0-9/_-]*)?$/i.test(base))throw Error('Güvenli HTTPS Worker adresi geçersiz.');if(!state.settings.token)throw Error('Erişim kodu ayarlanmamış.');let ac=new AbortController(),t=setTimeout(()=>ac.abort(),30000);try{let r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.token},body:JSON.stringify({messages:[{role:'system',content:systemPrompt()},...state.chat.slice(-10)],context:{level:currentLesson().level,title:currentLesson().title,rule:currentLesson().rule,mistakes:Object.values(state.misses).sort((a,b)=>b.errors-a.errors).slice(0,5).map(m=>m.title+' => '+m.answer)}}),signal:ac.signal});let body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||('HTTP '+r.status));answer=body.reply||'Boş AI yanıtı.';}finally{clearTimeout(t)}
}else throw Error('AI modu bilinmiyor.');state.chat.push({role:'assistant',content:String(answer).slice(0,2400)});activity();}catch(e){state.chat.push({role:'assistant',content:'Bağlantı/model sorunu: '+String(e.message||e)});}finally{isSending=false;save();if(page==='chat')renderChat();}}
function renderStats(){let done=completedCount(),acc=state.attempts?Math.round(state.correct/state.attempts*100):0,miss=Object.values(state.misses).filter(x=>x.errors>0).length;
root.innerHTML=`<div class="eyebrow">Progress & Review</div><h1>Gelişim paneli</h1><div class="grid2"><div class="kpi"><small>Tamamlanan ders</small><span class="num">${done}/24</span></div><div class="kpi"><small>Doğruluk</small><span class="num">%${acc}</span></div><div class="kpi"><small>Çözülen soru</small><span class="num">${state.attempts}</span></div><div class="kpi"><small>Çalışılan gün</small><span class="num">${state.days.length}</span></div></div><h2 class="section-title">Konu ilerlemesi</h2>${['A0','A1','A2'].map(l=>{let ls=LESSONS.filter(x=>x.level===l),d=ls.filter(x=>state.completed[x.id]?.score>=75).length;return `<div class="card"><div class="row between"><strong>${l}</strong><span class="muted">${d}/${ls.length} ders</span></div><div style="height:10px"></div><div class="progress"><div style="width:${d/ls.length*100}%"></div></div></div>`}).join('')}
<h2 class="section-title">Aralıklı tekrar</h2><div class="card"><p class="muted">Yanlış cevapladığın ${miss} soru takip ediliyor. Doğru tekrarlar sorunun bir sonraki tekrar tarihini ileri taşır.</p><button class="btn full" data-action="review">Bugünkü tekrarları çöz (${dueQuestions().length})</button></div><p class="tiny">İlerleme istatistikleri yalnızca iPhone'unun tarayıcı deposundadır. Veri kaybı riskine karşı Ayarlar'dan yedek al.</p>`;}
function renderSettings(){root.innerHTML=`<div class="eyebrow">Preferences & Privacy</div><h1>Ayarlar</h1><div class="card"><h3>AI çalışma modu</h3><p class="muted">Gerçek AI kullanımı için cihaz modeli ya da güvenli sunucu gereklidir.</p><label class="label" for="ai-mode">Öğretmen modu</label><select class="field" id="ai-mode"><option value="offline" ${state.settings.ai==='offline'?'selected':''}>Çevrimdışı hazır koç (AI değil)</option><option value="device" ${state.settings.ai==='device'?'selected':''}>iPhone'da küçük gerçek AI (deneysel)</option><option value="cloud" ${state.settings.ai==='cloud'?'selected':''}>Güvenli sunucuda güçlü gerçek AI</option></select><p class="tiny">Cihaz AI modu: ilk indirmenin büyüklüğü yüzlerce MB; Safari/WebGPU desteği ve hafıza kısıtlarına bağlıdır. Çevrimiçi mod: sohbet metinleri seçilen AI sağlayıcısına gider.</p><label class="label" for="worker">Worker HTTPS adresi (çevrimiçi mod)</label><input class="field" id="worker" type="url" placeholder="https://...workers.dev" value="${h(state.settings.worker)}" autocomplete="off"/><div style="height:10px"></div><label class="label" for="token">Kişisel Worker erişim kodu</label><input class="field" id="token" type="password" autocomplete="off" placeholder="API anahtarı değil; kendin belirlediğin erişim kodu" value="${h(state.settings.token)}"/></div>
<div class="card"><h3>Sesli eğitim</h3><label class="label" for="voice-rate">Okuma hızı: ${state.settings.voiceRate}x</label><input id="voice-rate" type="range" min="0.65" max="1.2" step="0.05" value="${state.settings.voiceRate}" style="width:100%"><p class="muted">iPhone'da bulunan İngilizce seslerden kadın sesine öncelik verilir. Tam olarak hangi sesin seçileceği yüklü iOS seslerine bağlıdır.</p><button class="btn secondary" data-action="test-voice">▶ Ses testini dinle</button></div>
<button class="btn full" data-action="save-settings">Ayarları kaydet</button><h2 class="section-title">Verilerim</h2><div class="card"><p class="muted">Tüm öğrenme kayıtları cihazındaki tarayıcıda saklanır. iOS depolama temizliği bu verileri silebilir; yedek almanı öneririm.</p><div class="grid2"><button class="btn secondary" data-action="export">Yedek indir</button><button class="btn secondary" data-action="import">Yedek yükle</button></div><input type="file" id="import-file" accept=".json,application/json" style="display:none"/><div style="height:16px"></div><button class="btn danger full" data-action="clear-progress">Tüm ilerlemeyi sıfırla</button></div><div class="card"><h3>iPhone uyumluluk kontrolü</h3><p class="muted">Ses, depolama ve iPhone üzerinde AI çalıştırma desteğini kontrol et.</p><button class="btn secondary full" data-action="diagnostics">Telefonumu kontrol et</button><div id="diagnostic-results"></div></div><div class="foot">English AI Teacher 1.0 · Developer: Ali Erkonak</div>`;
const f=document.getElementById('import-file');f.addEventListener('change',importBackup);}
function runDiagnostics(){let tests=[['Güvenli HTTPS bağlantısı',location.protocol==='https:'?'Uygun':'HTTPS yayın gerekir'],['Tarayıcı depolaması',(()=>{try{localStorage.setItem('__eai_test','ok');let ok=localStorage.getItem('__eai_test')==='ok';localStorage.removeItem('__eai_test');return ok?'Uygun':'Kullanılamıyor'}catch(e){return 'Kullanılamıyor'}})()],['İngilizce ses sentezi',typeof window.speechSynthesis!=='undefined'?'Mevcut':'Desteklenmiyor'],['Mikrofondan konuşma tanıma',window.SpeechRecognition||window.webkitSpeechRecognition?'API var; iPhone ana ekranında ayrıca denenmeli':'Klavye diktesi önerilir'],['Yerel AI WebGPU',navigator.gpu?'Destek var; model ayrıca denenmeli':'Destek bulunamadı'],['Çevrimdışı uygulama altyapısı','serviceWorker'in navigator?'Destek var':'Desteklenmiyor']];let el=document.getElementById('diagnostic-results');if(el)el.innerHTML='<div class="line"></div>'+tests.map(([k,v])=>`<p class="muted"><strong>${h(k)}:</strong> ${h(v)}</p>`).join('');}
function saveSettings(){let mode=document.getElementById('ai-mode').value,url=document.getElementById('worker').value.trim().replace(/\/$/,''),token=document.getElementById('token').value.trim(),rate=Number(document.getElementById('voice-rate').value);if(url&&!/^https:\/\/[a-z0-9.-]+(?:\/[a-z0-9/_-]*)?$/i.test(url)){toast('Worker adresi https:// ile başlamalı.');return;}state.settings={ai:mode,worker:url,token,autoplay:false,voiceRate:rate};save();toast('Ayarlar kaydedildi.');renderSettings();}
function exportBackup(){let data=JSON.parse(JSON.stringify(state));data.settings.token='';let payload={app:'english-ai-teacher',version:1,exported:new Date().toISOString(),data};let blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='EnglishAI_yedek_'+TODAY()+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function importBackup(e){let file=e.target.files?.[0];if(!file)return;try{if(file.size>2e6)throw Error('Dosya çok büyük.');let obj=JSON.parse(await file.text());if(obj.app!=='english-ai-teacher'||obj.version!==1||!obj.data||typeof obj.data.completed!=='object'||!Array.isArray(obj.data.chat))throw Error('Bu bir English AI yedeği değil.');if(!confirm('Mevcut kayıtların yedek ile değiştirilecek. Devam edilsin mi?'))return;state={...defaultState(),...obj.data,settings:{...defaultState().settings,...obj.data.settings}};save();go('home');toast('Yedek geri yüklendi.');}catch(err){toast('Yedek okunamadı: '+String(err.message||err).slice(0,80));}}
function clearProgress(){if(!confirm('Tüm ders ilerlemen ve sohbetlerin silinecek. Emin misin?'))return;if(!confirm('Bu işlem geri alınamaz. Devam etmek istiyor musun?'))return;let settings=state.settings;state=defaultState();state.settings=settings;save();go('home');toast('İlerleme sıfırlandı.');}
document.addEventListener('click',async e=>{let el=e.target.closest('[data-action],[data-page]');if(!el)return;if(el.dataset.page){go(el.dataset.page);return;}let a=el.dataset.action;switch(a){
case 'continue':state.activeLesson=currentLesson().id;save();go('lesson');break;
case 'open-lesson':{let idx=Number(el.dataset.index);if(!lessonUnlocked(idx))return;state.activeLesson=LESSONS[idx].id;save();go('lesson');break;}
case 'start-lesson-quiz':startLessonQuiz();break;
case 'choose':if(!quiz?.submitted){quiz.selected=quiz.questions[quiz.index].options[Number(el.dataset.index)];renderQuiz();}break;
case 'submit-answer':submitAnswer();break;
case 'next-question':nextQuestion();break;
case 'repeat-quiz':if(quiz.kind==='lesson')startLessonQuiz();else reviewQuiz();break;
case 'finish-quiz':{let l=quiz?.lesson,passed=quiz&&quiz.score/quiz.questions.length>=.75;quiz=null;if(l&&passed){state.activeLesson=nextLesson().id;save();go('lesson')}else if(l){state.activeLesson=l.id;save();go('lesson')}else go('stats');break;}
case 'review':reviewQuiz();break;
case 'speak':say(el.dataset.text);break;
case 'play-phrase':{let l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();say(l.examples[speakIndex%l.examples.length]);break;}
case 'record':startRecording();break;
case 'check-speak':checkSpeaking();break;
case 'next-phrase':{let l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();speakIndex=(speakIndex+1)%l.examples.length;heard='';speakFeedback='';renderSpeaking();break;}
case 'send':await sendChat();break;
case 'start-device':await loadDeviceModel();break;
case 'save-settings':saveSettings();break;
case 'test-voice':say('Hello! I am your English teacher. Let us learn together.');break;
case 'diagnostics':runDiagnostics();break;
case 'export':exportBackup();break;
case 'import':document.getElementById('import-file')?.click();break;
case 'clear-progress':clearProgress();break;
}});
if('serviceWorker'in navigator&&(location.protocol==='https:'||['localhost','127.0.0.1'].includes(location.hostname))){navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('Offline cache:',e));}
render();
