'use strict';
// Tutor-driven long-form lesson for any of 228 curriculum units. No fake completion and no paid API.
let detailedLessonBusy=false,detailedLessonError='';
function detailedLessonStore(){if(!state.detailedLessons||typeof state.detailedLessons!=='object')state.detailedLessons={};return state.detailedLessons;}
function detailedLessonHtml(l){const lesson=detailedLessonStore()[l.id];
 const btn=`<button class="btn secondary full" data-action="detailed-generate" ${detailedLessonBusy?'disabled':''}>${detailedLessonBusy?'AI ayrıntılı ders hazırlıyor…':lesson?'↻ AI dersini yeniden oluştur':'✦ AI ile kapsamlı ders hazırla'}</button>`;
 if(!lesson)return `<section class="premium-panel detailed-lesson-panel"><h2>✦ Kişisel ayrıntılı öğretim</h2><p class="muted">AI öğretmen konuyu Türkçe adım adım anlatır, İngilizce örnekler, kelimeler, okuma, sesli dinleme, yazma görevi ve konuşma sorusu üretir. Bu eğitim, resmî sınav yerine geçmez.</p>${btn}${detailedLessonError?`<p class="warning">${h(detailedLessonError)}</p>`:''}</section>`;
 const steps=Array.isArray(lesson.steps)?lesson.steps:[];
 const vocab=Array.isArray(lesson.vocabulary)?lesson.vocabulary:[];
 const mistakes=Array.isArray(lesson.mistakes)?lesson.mistakes:[];
 return `<section class="premium-panel detailed-lesson-panel"><span class="badge">AI öğretmenin hazırladığı ders</span><h2>${h(l.title)} — ayrıntılı öğretim</h2><p class="muted">Bu içerik AI tarafından üretildi; soruların ve önemli kuralların doğruluğunu dersin resmî kaynak içeriğiyle karşılaştır.</p><h3>1. Konunun Türkçe anlatımı</h3><p>${h(lesson.explanationTr)}</p><h3>2. Adım adım öğren</h3>${steps.map((x,i)=>`<div class="ai-lesson-step"><strong>${i+1}. ${h(x.title)}</strong><p>${h(x.explainTr)}</p><p class="lesson-example">${h(x.exampleEn)}<button class="speakbtn" data-action="speak" data-text="${h(x.exampleEn)}">▶</button></p><p class="muted">${h(x.meaningTr)}</p></div>`).join('')}<h3>3. Kritik hatalar</h3>${mistakes.map(x=>`<div class="ai-lesson-step"><span class="muted">Yanlış:</span> ${h(x.wrong)}<p><strong>Doğru:</strong> ${h(x.correct)}</p><p>${h(x.whyTr)}</p></div>`).join('')}<h3>4. Kelime ve kalıplar</h3>${vocab.map(x=>`<p class="word-pair"><strong>${h(x.en)}</strong> — ${h(x.tr)}<small>${h(x.example)}</small></p>`).join('')}<h3>5. Okuma</h3><p class="reading-text" lang="en">${h(lesson.readingEn)}</p>${(lesson.readingQuestions||[]).map((x,i)=>`<p><strong>Soru ${i+1}:</strong> ${h(x)}</p>`).join('')}<h3>6. Dinleme pratiği</h3><p class="muted">Metni görmeden önce dinle, sonra açıp karşılaştır.</p><button class="btn secondary" data-action="detailed-listen">🔊 Dinleme metnini oynat</button><details><summary>Dinleme metnini göster</summary><p lang="en">${h(lesson.listeningEn)}</p></details><h3>7. Yazma görevi</h3><p>${h(lesson.writingTaskTr)}</p><h3>8. Konuşma pratiği</h3><p lang="en">${h(lesson.speakingPromptEn)}</p><button class="btn full" data-action="coach-start">AI ile öğrendiklerini uygula →</button><div style="height:10px"></div>${btn}${detailedLessonError?`<div class="warning">${h(detailedLessonError)}</div>`:''}</section>`;
}
async function detailedLessonGenerate(){if(detailedLessonBusy)return;const l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();if(!directorReady()){detailedLessonError='AI ile ayrıntılı ders için Ayarlar kısmında Cloudflare Workers AI bağlantısını etkinleştir. Hazır ders anlatımı ve sorular çevrimdışı kullanılabilir.';renderLesson();return;}
 detailedLessonBusy=true;detailedLessonError='';renderLesson();const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),80000);
 try{const res=await fetch(state.settings.worker,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.token},body:JSON.stringify({action:'build_lesson',lesson:{id:l.id,level:l.level,title:l.title,rule:l.rule,objective:l.tr,examples:l.examples.slice(0,4)},weaknesses:[...(proEnabled(l)?[proMasterySummary(l).slice(0,200)]:[]),...Object.values(state.misses||{}).filter(x=>x?.errors>0).slice(-3).map(x=>String(x.title||'').slice(0,80))]}),signal:ctrl.signal});const data=await res.json();if(!res.ok)throw Error(data.error||'HTTP '+res.status);if(!data.lesson||!Array.isArray(data.lesson.steps)||data.lesson.steps.length<3)throw Error('AI dersi eksik hazırladı.');
 const store=detailedLessonStore();store[l.id]={...data.lesson,created:Date.now()};for(const key of Object.keys(store).sort((a,b)=>store[a].created-store[b].created).slice(0,Math.max(0,Object.keys(store).length-12)))delete store[key];save();
 }catch(e){detailedLessonError='Ders üretilemedi: '+String(e.message||e).slice(0,170)+' Hazır müfredat kullanılabilir.';}
 finally{clearTimeout(timer);detailedLessonBusy=false;if(page==='lesson')renderLesson();}
}
function detailedLessonListen(){const l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();const text=detailedLessonStore()[l.id]?.listeningEn;if(text)say(text,'en');}
