'use strict';
// Carefully authored supplementary CEFR micro-lessons – existing L01–L144 keys intact.
// Copyright (c) Ali Erkonak.
const MASTER_LESSON_UNITS = [
 {
  "level": "A0",
  "title": "İngilizce alfabe ve heceleme",
  "objective": "Harfleri adlarıyla söyle, özel isimlerini hecele.",
  "rule": "İngilizce harf adları ile kelimelerdeki sesler farklı olabilir; adını harf harf söylemek için How do you spell...? kullan.",
  "a": "How do you spell your name?",
  "at": "Adını nasıl hecelersin?",
  "b": "My name starts with A.",
  "bt": "Adım A harfiyle başlar.",
  "pitfall": "Büyük ve küçük harfleri ayrı öğren; A harfinin adı ile apple sözcüğündeki ses aynı değildir.",
  "id": "P001"
 },
 {
  "level": "A0",
  "title": "Temel sesler ve kısa ünlüler",
  "objective": "Kısa ünlüleri duyduğunda ayırt et.",
  "rule": "Cat sözcüğündeki /æ/ sesi ile cut sözcüğündeki /ʌ/ farklıdır; yazılan harf tek başına telaffuzu belirlemez.",
  "a": "Cat and cut sound different.",
  "at": "Cat ve cut sözcükleri farklı duyulur.",
  "b": "Listen and repeat the word.",
  "bt": "Kelimeyi dinle ve tekrar et.",
  "pitfall": "Yazıldığı gibi Türkçe okuma; önce dinle ve karşılaştır.",
  "id": "P002"
 },
 {
  "level": "A0",
  "title": "Sayılardan önce 0–20",
  "objective": "0–20 sayılarını ve telefon numarasını söyle.",
  "rule": "Thirteen ve thirty sesleri farklıdır; teen son ekini ve vurgu yerini dikkatle dinle.",
  "a": "I am thirteen years old.",
  "at": "Ben on üç yaşındayım.",
  "b": "My number is twelve.",
  "bt": "Numaram on iki.",
  "pitfall": "Thirteen ve thirty sözcüklerini karıştırma.",
  "id": "P003"
 },
 {
  "level": "A0",
  "title": "Renkler, temel şekiller ve eşyalar",
  "objective": "Renk ve temel nesneleri tanımla.",
  "rule": "Sıfat ismin önüne gelir: a blue bag. Be fiiliyle de tanımlayabilirsin: The bag is blue.",
  "a": "This is a red pen.",
  "at": "Bu kırmızı bir kalem.",
  "b": "The box is round.",
  "bt": "Kutu yuvarlaktır.",
  "pitfall": "A red pen sözcük sırasını red a pen şeklinde kurma.",
  "id": "P004"
 },
 {
  "level": "A0",
  "title": "A / an ve tekil isim",
  "objective": "Tekil sayılabilir isimlerde a/an seç.",
  "rule": "A/an harfe değil başlangıç sesine göre seçilir: an apple, a university. Bazı örnekler istisna gibi görünür.",
  "a": "It is an apple.",
  "at": "Bu bir elmadır.",
  "b": "This is a book.",
  "bt": "Bu bir kitaptır.",
  "pitfall": "An university yanlıştır çünkü university /juː/ sesiyle başlar.",
  "id": "P005"
 },
 {
  "level": "A0",
  "title": "This / that / these / those",
  "objective": "Yakın ve uzak nesneleri göster.",
  "rule": "This/that tekil; these/those çoğuldur. Nesne yakındaysa this veya these kullan.",
  "a": "This is my phone.",
  "at": "Bu benim telefonum.",
  "b": "Those are my shoes.",
  "bt": "Şunlar benim ayakkabılarım.",
  "pitfall": "These is değil these are kullanılır.",
  "id": "P006"
 },
 {
  "level": "A0",
  "title": "Aile üyeleri ve sahiplik",
  "objective": "Aileyi tanıt ve kime ait olduğunu söyle.",
  "rule": "My, your, his, her, our, their sözcükleri isimden önce sahiplik gösterir; Türkçe iyelik eki gibi düşün.",
  "a": "This is my sister.",
  "at": "Bu benim kız kardeşim.",
  "b": "Her name is Ece.",
  "bt": "Onun adı Ece.",
  "pitfall": "Her is Ece yerine she is Ece kullan.",
  "id": "P007"
 },
 {
  "level": "A0",
  "title": "Ülkeler, milliyetler ve diller",
  "objective": "Nereli olduğunu ve dilini ifade et.",
  "rule": "I am from ... ülke; I am Turkish milliyet; I speak Turkish dil bilgisidir.",
  "a": "I am from Turkey.",
  "at": "Ben Türkiye'denim.",
  "b": "I speak Turkish and English.",
  "bt": "Türkçe ve İngilizce konuşurum.",
  "pitfall": "I from Turkey yerine I am from Turkey yaz.",
  "id": "P008"
 },
 {
  "level": "A0",
  "title": "Haftanın günleri ve aylar",
  "objective": "Gün, ay ve basit takvim ifadelerini kullan.",
  "rule": "İngilizcede gün ve ay adları büyük harfle başlar; günler için on, aylar için in kullan.",
  "a": "I work on Monday.",
  "at": "Pazartesi çalışırım.",
  "b": "My birthday is in June.",
  "bt": "Doğum günüm hazirandadır.",
  "pitfall": "In Monday değil on Monday kullan.",
  "id": "P009"
 },
 {
  "level": "A0",
  "title": "Temel nezaket ve kısa cevaplar",
  "objective": "Selamlamalara doğal ve kibar yanıt ver.",
  "rule": "Please isteğe nezaket, thank you teşekkür, you're welcome karşılık için kullanılır.",
  "a": "Could you help me, please?",
  "at": "Bana yardım eder misiniz lütfen?",
  "b": "Thank you for your help.",
  "bt": "Yardımın için teşekkür ederim.",
  "pitfall": "Please ve sorry farklı niyetler içindir; birbirinin yerine kullanılmaz.",
  "id": "P010"
 },
 {
  "level": "A0",
  "title": "Basit soru-cevap diyalogları",
  "objective": "İsmini, durumunu, yaşını basit sorularla anlat.",
  "rule": "What is your name? isim sorar; How old are you? yaş sorar. Kısa cevap ve tam cevap ayrı olabilir.",
  "a": "What is your name?",
  "at": "Adın ne?",
  "b": "I am twenty years old.",
  "bt": "Ben yirmi yaşındayım.",
  "pitfall": "How many years are you? yerine How old are you? kullan.",
  "id": "P011"
 },
 {
  "level": "A0",
  "title": "İlk dinleme: kısa cümleler",
  "objective": "Yavaş söylenen tanışma cümlelerinin anlamını yakala.",
  "rule": "İlk dinlemede her kelimeyi çözmeye çalışma; ad, yer, sayı gibi anahtar bilgiyi seç.",
  "a": "Hello, my name is Emma.",
  "at": "Merhaba, benim adım Emma.",
  "b": "I live in Istanbul.",
  "bt": "İstanbul'da yaşıyorum.",
  "pitfall": "Dinlerken bilmediğin kelime yüzünden tüm cümleyi bırakma.",
  "id": "P012"
 },
 {
  "level": "A1",
  "title": "Simple Present olumsuz pratik",
  "objective": "Günlük rutinleri olumsuz söyle.",
  "rule": "I/you/we/they don't; he/she/it doesn't kullanır. Doesn't sonrası fiil yalın olur.",
  "a": "I don't drink coffee.",
  "at": "Kahve içmem.",
  "b": "She doesn't work on Sundays.",
  "bt": "O pazar günleri çalışmaz.",
  "pitfall": "She doesn't works değil she doesn't work yaz.",
  "id": "P013"
 },
 {
  "level": "A1",
  "title": "Saatler ve günlük plan",
  "objective": "Ders ve randevu saatlerini söyle.",
  "rule": "At seven, at half past six; önce saat sonra etkinliği söyle. Saatler için at kullan.",
  "a": "I wake up at seven.",
  "at": "Saat yedide uyanırım.",
  "b": "The lesson starts at nine.",
  "bt": "Ders dokuzda başlar.",
  "pitfall": "On nine değil at nine kullan.",
  "id": "P014"
 },
 {
  "level": "A1",
  "title": "Sıklık zarfları",
  "objective": "Always, usually, sometimes, never sözcüklerini kullan.",
  "rule": "Sıklık zarfı çoğu fiilden önce, be fiilinden sonra gelir.",
  "a": "I usually go to work by bus.",
  "at": "Genellikle işe otobüsle giderim.",
  "b": "She is always on time.",
  "bt": "O her zaman zamanında gelir.",
  "pitfall": "I am usually go değil I usually go yaz.",
  "id": "P015"
 },
 {
  "level": "A1",
  "title": "Sayılamayan isimler",
  "objective": "Much/many ve some kullanımlarını ayır.",
  "rule": "Water sayılamaz; bottles sayılabilir. Sayılamayan isimlerle a/an kullanılmaz.",
  "a": "I need some water.",
  "at": "Biraz suya ihtiyacım var.",
  "b": "How many apples do you want?",
  "bt": "Kaç elma istiyorsun?",
  "pitfall": "A water yerine some water veya a glass of water de.",
  "id": "P016"
 },
 {
  "level": "A1",
  "title": "Konum ve yer edatları",
  "objective": "In, on, under, behind ve between kullan.",
  "rule": "In içinde; on üstünde; under altında; between iki şey arasında anlamındadır.",
  "a": "The keys are on the table.",
  "at": "Anahtarlar masanın üzerindedir.",
  "b": "The bag is under the chair.",
  "bt": "Çanta sandalyenin altındadır.",
  "pitfall": "On ve in eş anlamlı değildir.",
  "id": "P017"
 },
 {
  "level": "A1",
  "title": "Kıyafet ve hava durumu",
  "objective": "Havaya uygun kıyafetleri konuş.",
  "rule": "It's sunny/raining; I'm wearing... kalıbında şu anda giyilen kıyafete -ing kullan.",
  "a": "It is cold today.",
  "at": "Bugün hava soğuk.",
  "b": "I am wearing a jacket.",
  "bt": "Ceket giyiyorum.",
  "pitfall": "I wearing değil I am wearing kullan.",
  "id": "P018"
 },
 {
  "level": "A1",
  "title": "Can ile izin ve yetenek",
  "objective": "Yetenek, izin ve ricayı ayır.",
  "rule": "Can + fiil yalın hâli; can to swim yanlıştır. Could daha kibar soru yapabilir.",
  "a": "I can swim.",
  "at": "Yüzebilirim.",
  "b": "Can I open the window?",
  "bt": "Pencereyi açabilir miyim?",
  "pitfall": "I can to swim değil I can swim.",
  "id": "P019"
 },
 {
  "level": "A1",
  "title": "Like, love, hate + ing",
  "objective": "Beğeni ve hobileri ifade et.",
  "rule": "Enjoy/like/love gibi fiillerden sonra isim ya da -ing biçimi gelebilir.",
  "a": "I like reading books.",
  "at": "Kitap okumayı severim.",
  "b": "She enjoys cooking.",
  "bt": "Yemek yapmaktan hoşlanır.",
  "pitfall": "She enjoys to cooking yanlış; enjoys cooking kullan.",
  "id": "P020"
 },
 {
  "level": "A1",
  "title": "Mağazada beden ve fiyat",
  "objective": "Beden sor ve fiyatı anla.",
  "rule": "How much is it? fiyat; Do you have this in medium? beden sorar.",
  "a": "How much is this shirt?",
  "at": "Bu gömlek ne kadar?",
  "b": "Do you have a larger size?",
  "bt": "Daha büyük bedeni var mı?",
  "pitfall": "How many money yerine how much money kullan.",
  "id": "P021"
 },
 {
  "level": "A1",
  "title": "Emir cümleleri ve yönergeler",
  "objective": "Basit tarifleri ve talimatları takip et.",
  "rule": "Olumlu emir fiille başlar: Open the door. Olumsuz: Don't + fiil.",
  "a": "Turn left at the corner.",
  "at": "Köşeden sola dön.",
  "b": "Don't touch the screen.",
  "bt": "Ekrana dokunma.",
  "pitfall": "Don't to touch değil don't touch kullan.",
  "id": "P022"
 },
 {
  "level": "A1",
  "title": "Kısa okuma: günlük mesaj",
  "objective": "Kısa bir mesajdaki kim/ne/zaman bilgisini ayır.",
  "rule": "Bir mesajı okurken önce kim yazdı, ne istedi, ne zaman cevap bekliyor sorularını yanıtla.",
  "a": "Please call me after lunch.",
  "at": "Lütfen öğle yemeğinden sonra beni ara.",
  "b": "See you tomorrow morning.",
  "bt": "Yarın sabah görüşürüz.",
  "pitfall": "After lunch ifadesini before lunch ile karıştırma.",
  "id": "P023"
 },
 {
  "level": "A1",
  "title": "Yazma: beş cümlelik günlük",
  "objective": "İsmini, yaşadığın yeri ve rutinini bir paragrafta yaz.",
  "rule": "İlk cümlede kendini tanıt, sonra iki rutin, bir sevdiğin şey ve kapanış yaz.",
  "a": "I live in Istanbul and I study English.",
  "at": "İstanbul'da yaşıyorum ve İngilizce çalışıyorum.",
  "b": "I go to the gym three times a week.",
  "bt": "Haftada üç kez spor salonuna giderim.",
  "pitfall": "Her cümleyi and ile uzatmak yerine kısa doğru cümleler kur.",
  "id": "P024"
 },
 {
  "level": "A2",
  "title": "Geçmiş zaman düzensiz fiiller",
  "objective": "Go/went, see/saw ve have/had biçimlerini öğren.",
  "rule": "Past Simple olumlu cümlede fiilin geçmiş hâli; did ile soruda yalın hâli gerekir.",
  "a": "I went to Ankara yesterday.",
  "at": "Dün Ankara'ya gittim.",
  "b": "Did you see the film?",
  "bt": "Filmi gördün mü?",
  "pitfall": "Did you went değil did you go kullan.",
  "id": "P025"
 },
 {
  "level": "A2",
  "title": "Seyahat: rezervasyon sorunu",
  "objective": "Bir rezervasyonu kontrol ettir ve problemi açıkla.",
  "rule": "I booked, but... ile sorunu açıkla; Could you check...? ile kibar rica et.",
  "a": "I booked a room for two nights.",
  "at": "İki gecelik oda ayırttım.",
  "b": "Could you check my reservation?",
  "bt": "Rezervasyonumu kontrol eder misiniz?",
  "pitfall": "Book fiilinin geçmişi booked biçimindedir.",
  "id": "P026"
 },
 {
  "level": "A2",
  "title": "Eczane ve sağlık belirtileri",
  "objective": "Hafif belirtileri anlatıp yardım iste.",
  "rule": "I have a headache veya I feel dizzy kullan; bu cümleler tanı değil, belirti anlatır.",
  "a": "I have a sore throat.",
  "at": "Boğazım ağrıyor.",
  "b": "I feel tired today.",
  "bt": "Bugün yorgun hissediyorum.",
  "pitfall": "I am have a headache yanlış; I have a headache yaz.",
  "id": "P027"
 },
 {
  "level": "A2",
  "title": "Karşılaştırma ve en üstünlük",
  "objective": "More, -er ve the most kullanımını ayır.",
  "rule": "Kısa sıfatlar genellikle -er/-est; uzun sıfatlar more/most alır; irregular: good/better/best.",
  "a": "This train is faster than the bus.",
  "at": "Bu tren otobüsten hızlıdır.",
  "b": "This is the best option.",
  "bt": "Bu en iyi seçenektir.",
  "pitfall": "More faster değil faster kullan.",
  "id": "P028"
 },
 {
  "level": "A2",
  "title": "Gelecek planı ve tahmin",
  "objective": "Going to plan, will tahmin/karar ayrımı yap.",
  "rule": "Önceden planlanan eylemler için going to; anlık karar veya bazı tahminler için will doğal olabilir.",
  "a": "I am going to visit London.",
  "at": "Londra'yı ziyaret edeceğim.",
  "b": "I think it will rain.",
  "bt": "Sanırım yağmur yağacak.",
  "pitfall": "I going to yerine I am going to yaz.",
  "id": "P029"
 },
 {
  "level": "A2",
  "title": "Geçmiş anlatım: while ve when",
  "objective": "Past Continuous ile geçmişteki olayı anlat.",
  "rule": "While + devam eden eylem, when + kısa olay ilişkisini anlamaya yardımcı olur.",
  "a": "I was cooking when she called.",
  "at": "O aradığında yemek yapıyordum.",
  "b": "They were walking in the park.",
  "bt": "Parkta yürüyorlardı.",
  "pitfall": "I was cook değil I was cooking kullan.",
  "id": "P030"
 },
 {
  "level": "A2",
  "title": "Modal: tavsiye ve zorunluluk",
  "objective": "Should, must ve have to farkını anla.",
  "rule": "Should tavsiye; must/have to zorunluluk bildirir; mustn't yasaklama anlamına gelir.",
  "a": "You should drink some water.",
  "at": "Biraz su içmelisin.",
  "b": "You must wear a seat belt.",
  "bt": "Emniyet kemeri takmalısın.",
  "pitfall": "Mustn't ile don't have to aynı anlamda değildir.",
  "id": "P031"
 },
 {
  "level": "A2",
  "title": "Neden ve sonuç bağlaçları",
  "objective": "Because, so, although ile açıklama kur.",
  "rule": "Because neden; so sonuç; although beklenenin tersine bir durum gösterir.",
  "a": "I stayed home because I was ill.",
  "at": "Hasta olduğum için evde kaldım.",
  "b": "Although it rained, we went out.",
  "bt": "Yağmur yağmasına rağmen dışarı çıktık.",
  "pitfall": "Because ve so'yu tek basit cümlede gereksiz çift kullanma.",
  "id": "P032"
 },
 {
  "level": "A2",
  "title": "Dinleme: ulaşım anonsları",
  "objective": "Uçuş saati, kapı ve gecikme bilgisini yakala.",
  "rule": "Önce sayı, saat, kapı numarası ve delayed gibi anahtar sözcükleri dinle.",
  "a": "The train leaves at six thirty.",
  "at": "Tren altı buçukta kalkıyor.",
  "b": "Your flight is delayed by one hour.",
  "bt": "Uçuşunuz bir saat gecikti.",
  "pitfall": "Departure ve arrival bilgilerini karıştırma.",
  "id": "P033"
 },
 {
  "level": "A2",
  "title": "Günlük e-posta ve mesaj",
  "objective": "Kibar ama kısa rica e-postası yaz.",
  "rule": "Hitap, neden yazdığın, isteğin ve kapanışı ayrı cümleler hâlinde düzenle.",
  "a": "Could you send me the address?",
  "at": "Bana adresi gönderir misiniz?",
  "b": "Thank you for your reply.",
  "bt": "Cevabınız için teşekkür ederim.",
  "pitfall": "Please you send yerine could you send kullan.",
  "id": "P034"
 },
 {
  "level": "A2",
  "title": "Okuma: ilan ve talimat",
  "objective": "Kısa ilanlarda koşul ve zamanları bul.",
  "rule": "Before, after, except ve only gibi ifadeler anlamı değiştirir; sorudaki anahtarları metinde ara.",
  "a": "The museum is closed on Mondays.",
  "at": "Müze pazartesileri kapalıdır.",
  "b": "Tickets are available online only.",
  "bt": "Biletler yalnızca çevrim içi alınabilir.",
  "pitfall": "Only kelimesini atlamak önemli bilgi kaybettirir.",
  "id": "P035"
 },
 {
  "level": "A2",
  "title": "Sohbet: görüş bildirme",
  "objective": "Kısa bir görüş ve bir gerekçe ver.",
  "rule": "I think..., because... yapısını kullan; nazik karşı görüşte I see your point, but... de.",
  "a": "I think this course is useful.",
  "at": "Bu kursun faydalı olduğunu düşünüyorum.",
  "b": "I prefer tea because it is lighter.",
  "bt": "Çayı tercih ederim çünkü daha hafiftir.",
  "pitfall": "I am agree değil I agree kullan.",
  "id": "P036"
 },
 {
  "level": "B1",
  "title": "Present Perfect vs Past Simple",
  "objective": "Deneyim ve belirli geçmiş zamanı ayır.",
  "rule": "Ever/never gibi deneyim ifadeleri Present Perfect ile; yesterday gibi belirli zamanlar Past Simple ile kullanılır.",
  "a": "I have visited Rome twice.",
  "at": "Roma'yı iki kez ziyaret ettim.",
  "b": "I visited Rome last year.",
  "bt": "Geçen yıl Roma'yı ziyaret ettim.",
  "pitfall": "I have visited Rome last year yerine I visited Rome last year yaz.",
  "id": "P037"
 },
 {
  "level": "B1",
  "title": "İkinci koşul cümlesi",
  "objective": "Gerçek dışı ya da hayalî durumu ifade et.",
  "rule": "If + Past Simple, would + yalın fiil; geçmiş biçim burada çoğu zaman varsayım gösterir.",
  "a": "If I had more time, I would travel.",
  "at": "Daha çok zamanım olsaydı seyahat ederdim.",
  "b": "I would help if I could.",
  "bt": "Yapabilsem yardım ederdim.",
  "pitfall": "If I would have değil if I had kullan.",
  "id": "P038"
 },
 {
  "level": "B1",
  "title": "Edilgen yapı: present/past",
  "objective": "Eylemi yapan yerine yapılan işi öne çıkar.",
  "rule": "Be + past participle; zaman be fiilinde görünür: is made, was made.",
  "a": "The report was sent yesterday.",
  "at": "Rapor dün gönderildi.",
  "b": "English is spoken worldwide.",
  "bt": "Dünyanın her yerinde İngilizce konuşulur.",
  "pitfall": "Was send değil was sent kullan.",
  "id": "P039"
 },
 {
  "level": "B1",
  "title": "Dolaylı anlatım giriş",
  "objective": "Başkasının sözünü doğru aktarmayı öğren.",
  "rule": "Say/tell ayrımı: He said that... / He told me that...; zaman dönüşümü bağlama bağlıdır.",
  "a": "She said that she was tired.",
  "at": "Yorgun olduğunu söyledi.",
  "b": "He told me the truth.",
  "bt": "Bana gerçeği söyledi.",
  "pitfall": "He told that yerine he said that veya he told me that kullan.",
  "id": "P040"
 },
 {
  "level": "B1",
  "title": "Bağlaçlarla uzun paragraf",
  "objective": "However, therefore ve in addition ile metin bağla.",
  "rule": "Her bağlacın işlevi farklıdır: however karşıtlık, therefore sonuç bildirir.",
  "a": "The plan was costly; however, it worked.",
  "at": "Plan pahalıydı; ancak işe yaradı.",
  "b": "Therefore, we changed the schedule.",
  "bt": "Bu yüzden programı değiştirdik.",
  "pitfall": "However ile because aynı anlamda değildir.",
  "id": "P041"
 },
 {
  "level": "B1",
  "title": "İş toplantısında görüş belirtme",
  "objective": "Kibarca fikir ve soru sun.",
  "rule": "Could I add something? ve From my perspective... kalıpları toplantıda söz almayı kolaylaştırır.",
  "a": "Could I add one point?",
  "at": "Bir noktayı ekleyebilir miyim?",
  "b": "I agree with the main goal.",
  "bt": "Ana hedefe katılıyorum.",
  "pitfall": "I agree to you yerine I agree with you kullan.",
  "id": "P042"
 },
 {
  "level": "B1",
  "title": "Telefonla sorun çözme",
  "objective": "Duyamadığında netleştirme ve tekrar iste.",
  "rule": "Could you repeat...? ve Let me confirm... anlamayı doğrular.",
  "a": "Could you repeat the last number?",
  "at": "Son numarayı tekrar eder misiniz?",
  "b": "Let me confirm the delivery date.",
  "bt": "Teslimat tarihini teyit edeyim.",
  "pitfall": "Repeat again gereksiz tekrar içerir.",
  "id": "P043"
 },
 {
  "level": "B1",
  "title": "Okuma: ana fikir ve çıkarım",
  "objective": "Paragraflarda doğrudan söylenmeyeni ayırt et.",
  "rule": "Önce ana fikri bul; çıkarımda metnin desteklemediği ayrıntılar ekleme.",
  "a": "The writer suggests a gradual change.",
  "at": "Yazar kademeli değişim öneriyor.",
  "b": "The main point is reducing waste.",
  "bt": "Ana fikir israfı azaltmaktır.",
  "pitfall": "Metinde yer almayan bilgiyi kesin sonuç sayma.",
  "id": "P044"
 },
 {
  "level": "B1",
  "title": "Dinleme: görüşme özeti",
  "objective": "Bir görüşmedeki üç temel noktayı kaydet.",
  "rule": "Kim konuştu, hangi karar alındı, kim ne yapacak sorularına odaklan.",
  "a": "We agreed to meet on Friday.",
  "at": "Cuma günü buluşmaya karar verdik.",
  "b": "The deadline has been moved.",
  "bt": "Son tarih değiştirildi.",
  "pitfall": "Agreed to sonrası yalın fiil kullanılır.",
  "id": "P045"
 },
 {
  "level": "B1",
  "title": "Yazma: olay ve deneyim",
  "objective": "Bir deneyimi kronolojik ve anlaşılır anlat.",
  "rule": "First/then/afterwards/finally ile olay sırası oluştur; temel geçmiş zaman tutarlı olsun.",
  "a": "At first, I felt nervous.",
  "at": "Başta gergin hissettim.",
  "b": "Finally, I solved the problem.",
  "bt": "Sonunda sorunu çözdüm.",
  "pitfall": "Zamanlar arasında gerekçesiz sıçrama yapma.",
  "id": "P046"
 },
 {
  "level": "B1",
  "title": "Phrasal verbs günlük kullanım",
  "objective": "Turn on, look after ve find out kalıplarını bağlamda öğren.",
  "rule": "Phrasal verb iki kelimeli olabilir, bazıları ayrılabilir; anlam kelime kelime çevrilmez.",
  "a": "Please turn off the lights.",
  "at": "Lütfen ışıkları kapat.",
  "b": "I found out the answer.",
  "bt": "Cevabı öğrendim.",
  "pitfall": "Find out yerine find up kullanma.",
  "id": "P047"
 },
 {
  "level": "B1",
  "title": "Sunum: problem-çözüm",
  "objective": "Kısa sunuma giriş, kanıt ve sonuç yerleştir.",
  "rule": "Today I will cover..., Firstly..., In conclusion... ile dinleyiciye yapı sun.",
  "a": "Today I will explain our proposal.",
  "at": "Bugün önerimizi açıklayacağım.",
  "b": "In conclusion, we need more data.",
  "bt": "Sonuç olarak daha fazla veriye ihtiyacımız var.",
  "pitfall": "In conclusion ardından bütün sunumu tekrar etme.",
  "id": "P048"
 },
 {
  "level": "B2",
  "title": "Üçüncü koşul: geçmiş varsayım",
  "objective": "Gerçekte olmamış geçmiş olayı yorumla.",
  "rule": "If + had V3, would have V3 biçimi geçmişteki varsayımsal sonucu anlatır.",
  "a": "If I had known, I would have called.",
  "at": "Bilseydim arardım.",
  "b": "We would have arrived earlier.",
  "bt": "Daha erken varmış olurduk.",
  "pitfall": "If I would have known yanlış; if I had known kullan.",
  "id": "P049"
 },
 {
  "level": "B2",
  "title": "Mixed Conditionals",
  "objective": "Geçmiş sebep ile bugünkü sonucu bağla.",
  "rule": "If I had studied..., I would know... yapısında zamanların neden farklı olduğuna dikkat et.",
  "a": "If I had studied harder, I would feel ready now.",
  "at": "Daha çok çalışmış olsaydım şimdi hazır hissederdim.",
  "b": "I would be happier now.",
  "bt": "Şimdi daha mutlu olurdum.",
  "pitfall": "Şimdiki sonuç için her zaman would have kullanma.",
  "id": "P050"
 },
 {
  "level": "B2",
  "title": "Modal deduction",
  "objective": "Must have, might have, can't have ile çıkarım yap.",
  "rule": "Geçmiş çıkarımda modal + have + V3 kullanılır; kesinlik derecesi değişir.",
  "a": "She must have forgotten the meeting.",
  "at": "Toplantıyı unutmuş olmalı.",
  "b": "He might have missed the train.",
  "bt": "Treni kaçırmış olabilir.",
  "pitfall": "Must had yerine must have kullan.",
  "id": "P051"
 },
 {
  "level": "B2",
  "title": "Cleft sentences",
  "objective": "Vurguyu özel cümle yapısıyla kur.",
  "rule": "It was ... that/who yapısı vurgulanacak öğeyi öne çıkarır.",
  "a": "It was Anna who solved the problem.",
  "at": "Sorunu çözen Anna'ydı.",
  "b": "What we need is a clear plan.",
  "bt": "İhtiyacımız olan açık bir plan.",
  "pitfall": "It is was gibi iki be fiilini üst üste yazma.",
  "id": "P052"
 },
 {
  "level": "B2",
  "title": "Hedging ve iddia gücü",
  "objective": "May, appear, tend to ile temkinli iddia kur.",
  "rule": "Kesin olmayan veri için appears to, may suggest, likely kullan.",
  "a": "The results appear to support the claim.",
  "at": "Sonuçlar iddiayı destekliyor gibi görünüyor.",
  "b": "This may lead to delays.",
  "bt": "Bu gecikmelere neden olabilir.",
  "pitfall": "Az kanıtla kesinlikle will demek yerine may kullan.",
  "id": "P053"
 },
 {
  "level": "B2",
  "title": "Müzakere ve uzlaşma dili",
  "objective": "Koşullu teklif ve alternatif üret.",
  "rule": "If we..., could you...? ile şartı; we could also ile alternatifi sun.",
  "a": "If we pay early, could you reduce the price?",
  "at": "Erken ödersek fiyatı düşürür müsünüz?",
  "b": "We could consider another option.",
  "bt": "Başka bir seçeneği değerlendirebiliriz.",
  "pitfall": "Could you to reduce değil could you reduce kullan.",
  "id": "P054"
 },
 {
  "level": "B2",
  "title": "İş yazışmasında diplomasi",
  "objective": "Doğrudan emri daha kibar ricaya dönüştür.",
  "rule": "Would you mind...? ve I would appreciate it if... kalıpları için doğru fiil biçimini seç.",
  "a": "I would appreciate an update by Friday.",
  "at": "Cuma gününe kadar güncelleme rica ederim.",
  "b": "Could you clarify the next step?",
  "bt": "Sonraki adımı netleştirir misiniz?",
  "pitfall": "I would appreciate you to send yerine appreciate it if you sent kullan.",
  "id": "P055"
 },
 {
  "level": "B2",
  "title": "Okuma: önyargı ve kanıt",
  "objective": "Yazarın iddiasını örneklerden ayır.",
  "rule": "Evidence ve opinion ayrımı, source/assumption analizi eleştirel okumayı geliştirir.",
  "a": "The author provides limited evidence.",
  "at": "Yazar sınırlı kanıt sunuyor.",
  "b": "This argument rests on an assumption.",
  "bt": "Bu iddia bir varsayıma dayanıyor.",
  "pitfall": "Örneği kanıtın tamamı olarak varsayma.",
  "id": "P056"
 },
 {
  "level": "B2",
  "title": "Dinleme: fikir ayrılığı",
  "objective": "Konuşmacıların görüşünü ve gerekçelerini çıkar.",
  "rule": "However, nevertheless ve I doubt gibi ipuçları karşı görüşü gösterir.",
  "a": "I see your point, but I disagree.",
  "at": "Görüşünü anlıyorum ama katılmıyorum.",
  "b": "The evidence is not convincing.",
  "bt": "Kanıt ikna edici değil.",
  "pitfall": "I doubt biçimini kesin onay gibi anlama.",
  "id": "P057"
 },
 {
  "level": "B2",
  "title": "Yazma: artı-eksi makalesi",
  "objective": "İki tarafı dengeleyip gerekçeli sonuç yaz.",
  "rule": "Bir paragraf lehte, bir paragraf aleyhte argüman sunsun; sonuç gerekçeli olsun.",
  "a": "One advantage is greater flexibility.",
  "at": "Bir avantajı daha fazla esnekliktir.",
  "b": "On the other hand, costs may increase.",
  "bt": "Öte yandan maliyetler artabilir.",
  "pitfall": "Her paragrafta yeni argümana geçip bağlantıyı kaybetme.",
  "id": "P058"
 },
 {
  "level": "B2",
  "title": "İleri phrasal verbs",
  "objective": "Put off, carry out ve bring up anlamlarını ayır.",
  "rule": "Formal bağlamda carry out a review denebilir, put off postponement anlamına gelir.",
  "a": "We carried out a detailed review.",
  "at": "Ayrıntılı bir inceleme yaptık.",
  "b": "They put off the meeting.",
  "bt": "Toplantıyı ertelediler.",
  "pitfall": "Carry on ve carry out her zaman aynı değildir.",
  "id": "P059"
 },
 {
  "level": "B2",
  "title": "Proje yönetimi konuşmaları",
  "objective": "Gecikme, risk ve seçenekleri net açıkla.",
  "rule": "Risk, impact, mitigation sözcüklerini somut eylem ve tarih ile birlikte kullan.",
  "a": "The delay may affect the deadline.",
  "at": "Gecikme son tarihi etkileyebilir.",
  "b": "We need a backup plan.",
  "bt": "Bir yedek plana ihtiyacımız var.",
  "pitfall": "Risk sözcüğünü yalnızca bir olayı olmuş gibi anlatmak için kullanma.",
  "id": "P060"
 },
 {
  "level": "C1",
  "title": "Nominalisation akademik dil",
  "objective": "Fiil cümlelerini adlaştırarak yoğun bilgi aktar.",
  "rule": "Decide → decision gibi adlaştırmalar resmî üslup verir ama aşırı kullanımı netliği azaltır.",
  "a": "The implementation requires careful planning.",
  "at": "Uygulama dikkatli planlama gerektirir.",
  "b": "Their decision affected the outcome.",
  "bt": "Kararları sonucu etkiledi.",
  "pitfall": "Her fiili adlaştırmak cümleyi gereksiz zorlaştırır.",
  "id": "P061"
 },
 {
  "level": "C1",
  "title": "Register ve ton yönetimi",
  "objective": "Aynı bilgiyi resmî ya da samimi tona uyarlama.",
  "rule": "İfadenin amacı, alıcısı ve kurumsal bağlamına göre sözcük ve rica biçimi seç.",
  "a": "We regret to inform you of the delay.",
  "at": "Gecikmeyi bildirmekten üzgünüz.",
  "b": "Sorry, I'm running late.",
  "bt": "Üzgünüm, gecikiyorum.",
  "pitfall": "Gündelik sorry ile resmî we regret her durumda birbirinin yerine geçmez.",
  "id": "P062"
 },
 {
  "level": "C1",
  "title": "Inversion for emphasis",
  "objective": "Never, rarely, not only ile devrik vurgu kur.",
  "rule": "Olumsuz zarf başa gelince yardımcı fiil özneden önce gelir: Never have I seen...",
  "a": "Never have I seen such a result.",
  "at": "Böyle bir sonuç hiç görmedim.",
  "b": "Not only did she finish early, but she also helped.",
  "bt": "Sadece erken bitirmedi, ayrıca yardım da etti.",
  "pitfall": "Never I have seen yerine Never have I seen kullan.",
  "id": "P063"
 },
 {
  "level": "C1",
  "title": "Advanced relative clauses",
  "objective": "Non-defining relative clause ve reduced clause ayır.",
  "rule": "Virgüllü relative clause ek bilgi verir; gerekli bilgi virgülle ayrılmamalıdır.",
  "a": "My manager, who lives in London, called.",
  "at": "Londra'da yaşayan yöneticim aradı.",
  "b": "The report published yesterday is useful.",
  "bt": "Dün yayımlanan rapor faydalıdır.",
  "pitfall": "Who lives in London biçimini özne anlamını bozacak şekilde düşürme.",
  "id": "P064"
 },
 {
  "level": "C1",
  "title": "Rhetorical argumentation",
  "objective": "Tez, karşı görüş ve itirazı etkili bağla.",
  "rule": "A credible argument acknowledges limits and addresses objections directly.",
  "a": "Admittedly, the approach has limitations.",
  "at": "Kabul etmek gerekir ki yaklaşımın sınırlamaları var.",
  "b": "Nevertheless, the benefits are significant.",
  "bt": "Bununla birlikte yararları önemli.",
  "pitfall": "Admittedly sözcüğünden sonra yalnızca tek taraflı övgü sıralama.",
  "id": "P065"
 },
 {
  "level": "C1",
  "title": "Paraphrase and synthesis",
  "objective": "Kaynakların fikrini anlam kaybı olmadan yeniden yaz.",
  "rule": "Sadece eş anlamlı sözcük değiştirme; yapı ve odak da yeniden düzenlenmeli.",
  "a": "Several studies suggest a similar trend.",
  "at": "Bazı çalışmalar benzer eğilim gösteriyor.",
  "b": "The findings can be interpreted differently.",
  "bt": "Bulgular farklı yorumlanabilir.",
  "pitfall": "Kaynağın belirsizliğini silerek kesin sonuç yazma.",
  "id": "P066"
 },
 {
  "level": "C1",
  "title": "Dinleme: ima ve tutum",
  "objective": "Konuşmacının sözünden niyet ve tutumu çıkar.",
  "rule": "Irony, understatement ve hesitation yalnızca sözcükten değil bağlamdan anlaşılır.",
  "a": "That is not exactly what I expected.",
  "at": "Tam da beklediğim şey bu değildi.",
  "b": "I suppose we could revisit the plan.",
  "bt": "Sanırım planı tekrar gözden geçirebiliriz.",
  "pitfall": "I suppose ifadesini güçlü kesin onay gibi görme.",
  "id": "P067"
 },
 {
  "level": "C1",
  "title": "Akademik sunum ve tartışma",
  "objective": "Gerekçe ve sınırlamaları sunumda değerlendir.",
  "rule": "Let me outline..., Turning to..., To conclude... ile mantıklı akış oluştur.",
  "a": "Let me outline the main findings.",
  "at": "Ana bulguları özetleyeyim.",
  "b": "These results should be interpreted cautiously.",
  "bt": "Bu sonuçlar dikkatle yorumlanmalıdır.",
  "pitfall": "Data sınırlıysa prove fiiliyle kesinlik iddia etme.",
  "id": "P068"
 },
 {
  "level": "C1",
  "title": "Eleştirel makale yazımı",
  "objective": "Tartışmalı konuda dengeli, kaynaklı argüman yaz.",
  "rule": "Claim, evidence, counterargument, rebuttal adımlarını ayrı paragrafta kullan.",
  "a": "A key limitation is the sample size.",
  "at": "Önemli bir sınırlama örneklem büyüklüğüdür.",
  "b": "The counterargument deserves consideration.",
  "bt": "Karşı görüş değerlendirmeyi hak ediyor.",
  "pitfall": "Karşı görüşü ele almadan yalnızca tekrar eden iddialar yazma.",
  "id": "P069"
 },
 {
  "level": "C1",
  "title": "İleri iş hukuku/etik dili",
  "objective": "Kurum içi etik ve uyum meselelerini tartış.",
  "rule": "Must comply with..., raises concerns about... gibi kalıpları hukuk danışmanlığı gibi sunmadan kullan.",
  "a": "The policy raises privacy concerns.",
  "at": "Politika gizlilik endişeleri doğuruyor.",
  "b": "We must comply with internal rules.",
  "bt": "İç kurallara uymak zorundayız.",
  "pitfall": "Comply to değil comply with kullan.",
  "id": "P070"
 },
 {
  "level": "C1",
  "title": "Teknik raporlama ve kök neden",
  "objective": "Sorun, gözlem, bulgu ve eylemi ayır.",
  "rule": "Root cause ile symptom farklıdır; evidence ve recommendation ayrı belirtilmelidir.",
  "a": "The failure was traced to a configuration error.",
  "at": "Arızanın kaynağı yapılandırma hatasıydı.",
  "b": "We recommend validating the input data.",
  "bt": "Giriş verilerini doğrulamayı öneriyoruz.",
  "pitfall": "Correlation görüldü diye root cause kesin denemez.",
  "id": "P071"
 },
 {
  "level": "C1",
  "title": "Kültürlerarası pragmatik",
  "objective": "Doğrudanlık ve nezaket seçimini bağlama göre yap.",
  "rule": "Bir dilsel ifadenin uygunluğu yalnızca gramer değil ilişki ve bağlama da bağlıdır.",
  "a": "Would you mind elaborating on that?",
  "at": "Bunu biraz açar mısınız?",
  "b": "I appreciate your perspective.",
  "bt": "Bakış açınızı takdir ediyorum.",
  "pitfall": "Her kültürde tek bir cümleyi evrensel derecede nazik sayma.",
  "id": "P072"
 },
 {
  "level": "C2",
  "title": "Üslup inceliği ve satır arası",
  "objective": "İma, küçümseme ve dolaylı mesajları ayırt et.",
  "rule": "Irony ve understatement bağlamla yorumlanır; düz anlam her zaman niyet değildir.",
  "a": "That was hardly a flawless performance.",
  "at": "Bu kusursuz bir performans sayılmazdı.",
  "b": "I wouldn't go quite that far.",
  "bt": "Ben o kadar ileri gitmezdim.",
  "pitfall": "Hardly sözcüğünü olumlu onay gibi yorumlama.",
  "id": "P073"
 },
 {
  "level": "C2",
  "title": "Karmaşık fikirleri sentezleme",
  "objective": "Çatışan görüşleri dürüstçe uzlaştır.",
  "rule": "Bir sentez, iki görüşü yan yana koymaktan öte hangi koşullarda geçerli olduklarını açıklar.",
  "a": "Both approaches have merit under different conditions.",
  "at": "Her iki yaklaşım da farklı koşullarda değerlidir.",
  "b": "A balanced synthesis requires context.",
  "bt": "Dengeli bir sentez bağlam gerektirir.",
  "pitfall": "Karşıt görüşü yanlış temsil ederek sentez yapma.",
  "id": "P074"
 },
 {
  "level": "C2",
  "title": "High-stakes diplomatic language",
  "objective": "Hassas iş görüşmelerinde bağlamı ve riski yönet.",
  "rule": "Açık sözlülükle kibar sınır belirlemeyi birlikte uygula; sorunlu varsayımı kişiselleştirme.",
  "a": "We may need to revisit that assumption.",
  "at": "Bu varsayımı yeniden gözden geçirmemiz gerekebilir.",
  "b": "I appreciate the concern, although I differ.",
  "bt": "Endişenizi anlıyorum ama farklı düşünüyorum.",
  "pitfall": "Diplomatik dilde mesajı tamamen belirsiz hâle getirme.",
  "id": "P075"
 },
 {
  "level": "C2",
  "title": "Literary devices and allusion",
  "objective": "Mecaz, imge, gönderme ve çağrışımı çöz.",
  "rule": "Metaforun sözcük anlamı ile bağlamdaki etkisini ayır; tarihsel/kültürel göndermeyi kanıtsız uydurma.",
  "a": "The city was a sea of lights.",
  "at": "Şehir bir ışık deniziydi.",
  "b": "His words carried an echo of regret.",
  "bt": "Sözlerinde pişmanlığın yankısı vardı.",
  "pitfall": "Mecazı her zaman gerçek bir fiziksel olay gibi okuma.",
  "id": "P076"
 },
 {
  "level": "C2",
  "title": "Advanced editing and economy",
  "objective": "Anlamı koruyarak karmaşık metni sadeleştir.",
  "rule": "Gereksiz tekrar, belirsiz referans ve yanlış sözcük eşdizimini düzelt.",
  "a": "The proposal lacks adequate justification.",
  "at": "Öneride yeterli gerekçe bulunmuyor.",
  "b": "We need a concise but accurate summary.",
  "bt": "Kısa ama doğru bir özete ihtiyacımız var.",
  "pitfall": "Kısaltırken kanıtın sınırlarını silme.",
  "id": "P077"
 },
 {
  "level": "C2",
  "title": "Debate: steelmanning",
  "objective": "Karşı görüşü en güçlü hâliyle ifade ederek tartış.",
  "rule": "Karşı tarafın argümanını adil aktarmak, eleştirinin kalitesini artırır.",
  "a": "The strongest case for this view is economic.",
  "at": "Bu görüşün en güçlü gerekçesi ekonomiktir.",
  "b": "Even so, the evidence remains incomplete.",
  "bt": "Buna rağmen kanıt eksik kalıyor.",
  "pitfall": "Karşı görüşü kolayca çürütmek için zayıflatma.",
  "id": "P078"
 },
 {
  "level": "C2",
  "title": "Humour and subtle sarcasm",
  "objective": "İnce alay ve sözcük oyunlarını bağlamda ayırt et.",
  "rule": "Sarcasm ses tonu kadar bağlamla da anlaşılır; metinden niyeti kesin ölçmek mümkün değildir.",
  "a": "Well, that went brilliantly, didn't it?",
  "at": "Eh, harika gitti, değil mi?",
  "b": "What a remarkably convenient coincidence.",
  "bt": "Ne kadar da dikkat çekici bir tesadüf.",
  "pitfall": "Her olumsuz sözü alay olarak sınıflama.",
  "id": "P079"
 },
 {
  "level": "C2",
  "title": "Academic peer review response",
  "objective": "Eleştiriye kanıtla ve nezaketle cevap ver.",
  "rule": "Hakemin itirazını özetle, değişikliği belirt, nedenini kaynakla açıkla.",
  "a": "We thank the reviewer for this observation.",
  "at": "Bu gözlem için hakeme teşekkür ederiz.",
  "b": "We have revised the relevant section.",
  "bt": "İlgili bölümü gözden geçirdik.",
  "pitfall": "Eleştiriyi yanıtsız bırakıp yalnızca teşekkür etme.",
  "id": "P080"
 },
 {
  "level": "C2",
  "title": "Executive communication",
  "objective": "Yöneticiye kısa, kanıta dayalı karar notu yaz.",
  "rule": "Önce öneri ve risk, sonra seçenekler ve ölçülebilir gerekçe sun.",
  "a": "We recommend proceeding with safeguards.",
  "at": "Koruyucu önlemlerle ilerlemeyi öneriyoruz.",
  "b": "The primary trade-off is cost versus speed.",
  "bt": "Temel ödünleşim maliyet ve hız arasındadır.",
  "pitfall": "Yönetici özetini ayrıntılı teknik raporla karıştırma.",
  "id": "P081"
 },
 {
  "level": "C2",
  "title": "Near-native collocation",
  "objective": "Doğal kelime birlikteliklerini uygun bağlamda seç.",
  "rule": "Strong coffee, heavy rain ve make a decision gibi kalıpları sözlükte birlikte öğren.",
  "a": "We need to make an informed decision.",
  "at": "Bilgiye dayalı karar vermemiz gerekiyor.",
  "b": "The region experienced heavy rainfall.",
  "bt": "Bölge yoğun yağış yaşadı.",
  "pitfall": "Do a decision değil make a decision kullan.",
  "id": "P082"
 },
 {
  "level": "C2",
  "title": "Nuanced translation and register",
  "objective": "Anlam, ton ve kültürel karşılığı beraber koru.",
  "rule": "İyi çeviri her sözcüğü birebir eşleştirmek değil niyet, üslup ve doğruluğu taşımaktır.",
  "a": "I would welcome a more detailed explanation.",
  "at": "Daha ayrıntılı bir açıklamayı memnuniyetle karşılarım.",
  "b": "The remark was intended as a gentle warning.",
  "bt": "Söz hafif bir uyarı olarak söylenmişti.",
  "pitfall": "Türkçe resmî hitabı her durumda kelimesi kelimesine çevirme.",
  "id": "P083"
 },
 {
  "level": "C2",
  "title": "Independent proficiency portfolio",
  "objective": "Dört beceriden örneklerle gerçek yeterlik kanıtı oluştur.",
  "rule": "Seviye iddiası tek mini sınavla değil yazma, okuma, dinleme ve uzun konuşma örnekleriyle desteklenmelidir.",
  "a": "I can defend a complex position with evidence.",
  "at": "Karmaşık bir görüşü kanıtla savunabilirim.",
  "b": "My writing needs greater precision.",
  "bt": "Yazımın daha yüksek kesinliğe ihtiyacı var.",
  "pitfall": "Bir AI sohbetine bakarak kesin C2 sertifikası varmış gibi düşünme.",
  "id": "P084"
 }
];

(function extendAccreditedCurriculum(){
 const levels=['A0','A1','A2','B1','B2','C1','C2'];
 for(const r of MASTER_LESSON_UNITS){
  const same=MASTER_LESSON_UNITS.filter(x=>x.level===r.level),at=same.indexOf(r);
  const distract=[same[(at+3)%same.length].at,same[(at+7)%same.length].bt];
  const masked=r.b.split(/\s+/),target=masked.find((w,i)=>i>1&&/^[a-zA-Z]{3,}/.test(w))||masked[masked.length-1];
  const missing=target.replace(/^[^A-Za-z]+|[^A-Za-z]+$/g,'');
  const question=r.b.replace(target,'___');
  const lessons=[
   {type:'choice',q:`“${r.a}” cümlesinin doğru Türkçesi hangisi?`,options:[r.at,...distract],answers:[r.at],why:`${r.a} = ${r.at}`},
   {type:'fill',q:`Eksik kelimeyi yaz: ${question}`,options:[],answers:[missing],why:`Tam cümle: ${r.b}`},
   {type:'translate',q:`Türkçeyi İngilizce yaz: ${r.at}`,options:[],answers:[r.a],why:`Doğru örnek: ${r.a}`},
   {type:'choice',q:`“${r.b}” cümlesinin anlamı nedir?`,options:[r.bt,...distract],answers:[r.bt],why:`${r.b} = ${r.bt}`}
  ];
  LESSONS.push({id:r.id,level:r.level,title:r.title,tr:r.objective,rule:r.rule,examples:[r.a,r.b],questions:lessons});
  LESSON_GUIDES[r.id]={intro:r.rule,steps:[`Kazanım: ${r.objective}`,r.rule,`Örnek 1: ${r.a} — ${r.at}`,`Örnek 2: ${r.b} — ${r.bt}`,`Şimdi kendi yaşamınla ilgili iki ayrı cümle kur; AI öğretmene denetlet.`],mistake:r.pitfall,meanings:[r.at,r.bt]};
 }
 // A0→C2 order is pedagogically crucial. Stable lesson IDs keep historical records safe.
 LESSONS.sort((a,b)=>levels.indexOf(a.level)-levels.indexOf(b.level));
})();
function masteryLessonAddon(l){const r=MASTER_LESSON_UNITS.find(x=>x.id===l.id);if(!r)return '';
 return `<section class="premium-panel mastery-unit"><h2>Ünite kazanımları</h2><p>${h(r.objective)}</p><ol><li>${h(r.rule)}</li><li>${h(r.a)} — ${h(r.at)}</li><li>${h(r.b)} — ${h(r.bt)}</li><li>Dinle, cümleyi yeniden kur, sonra kendi örneğini söyle.</li></ol><div class="note"><strong>Sık yapılan hata:</strong> ${h(r.pitfall)}</div><p class="muted">AI öğretmen bu konuda sana yeni ve kişisel örnekler, ödevler ve düzeltmeler hazırlayabilir.</p></section>`;
}
