"use strict";
// v2.5 teacher-led school module. Developer: Ali Erkonak.
// Never replaces existing v1 localStorage key or removes prior progress.
let tutorExplanationBusy=false,tutorExplanationError='',tutorHomeworkBusy=false,tutorHomeworkError='',tutorReplyBusy=false,tutorReplyError='';
const tutorAutoTried=new Set();
const TEACHER_LECTURES={
 L01:['Tanışmada önce selam ver, sonra adını söyle ve karşındakine basit bir soru sor.','Hello! → My name is Ali. → Nice to meet you.','My name Ali. cümlesinde is eksik.'],
 L02:['İngilizcede “ben ...im” derken am, “sen ...sin” derken are kullanılır. Türkçedeki ek yerine ayrı sözcük gerekir.','I am happy. / You are happy.','I from Turkey. değil I am from Turkey.'],
 L03:['Önce kişinin veya nesnenin kim olduğuna karar ver; sonra he/she/it ile is kullan.','He is a teacher. / She is at home.','He are yerine He is kullanılır.'],
 L04:['Soru yapmak için yardımcı be fiilini özneden önceye taşı.','You are ready. → Are you ready?','Are you from Turkey? / Where are you from?'],
 L05:['Her gün olan rutinleri Present Simple ile anlat. I/you ile fiil yalın olur.','I study English every day.','I am study every day yanlış; am yalnızca -ing yapısıyla kullanılır.'],
 L06:['He/she/it ile geniş zaman olumlu fiiline çoğunlukla -s ekle.','I work. → She works.','She work değil She works.'],
 L07:['Geniş zaman sorusunda do/does başa gelir; esas fiil yalın kullanılır.','Do you work? / Does he work?','Does he works? değil Does he work?'],
 L08:['Olumsuz rutinlerde don’t / doesn’t kullan. Doesn’t sonrası fiil yalın kalır.','I don’t work on Sunday.','He doesn’t works değil He doesn’t work.'],
 L09:['Şu anda sürmekte olan iş için am/is/are + fiil-ing kullan.','I am studying now.','I am study now değil I am studying now.'],
 L10:['Rutin ve şimdiyi ayır: every day → Simple; now → Continuous.','I work every day. / I am working now.','I am usually get up değil I usually get up.'],
};
function teacherStore(){if(!state.homework||typeof state.homework!=='object'||Array.isArray(state.homework))state.homework={};if(!state.tutorExplanations||typeof state.tutorExplanations!=='object')state.tutorExplanations={};if(!Array.isArray(state.tutorHistory))state.tutorHistory=[];if(!state.tutorDialogs||typeof state.tutorDialogs!=='object')state.tutorDialogs={};return state.homework;}
function teacherAssignment(l=currentLesson()){
 const store=teacherStore();if(!store[l.id]){
  store[l.id]={lessonId:l.id,assignedAt:Date.now(),dueAt:Date.now()+86400000,answers:{},attempts:0,status:'assigned',score:null,objective:[],aiReview:null,submittedAt:null};save();
 }
 return store[l.id];
}
function teacherPendingAssignments(){teacherStore();return Object.values(state.homework).filter(x=>x&&x.status!=='completed').sort((a,b)=>a.dueAt-b.dueAt);}
function teacherRecommendedLesson(){const pending=teacherPendingAssignments();const overdue=pending.find(x=>x.dueAt<Date.now());if(overdue)return {type:'homework',lesson:LESSONS.find(l=>l.id===overdue.lessonId)||currentLesson()};if(dueQuestions().length)return {type:'review',lesson:currentLesson()};return {type:'lesson',lesson:currentLesson()};}
function teacherOneLine(l){return (TEACHER_LECTURES[l.id]||[LESSON_GUIDES[l.id]?.intro||l.rule])[0];}
function teacherLessonAddon(l){teacherStore();const theory=TEACHER_LECTURES[l.id],exp=state.tutorExplanations[l.id];let a=teacherAssignment(l);return `<div class="teacher-path"><div class="row between"><span class="badge">Öğretmen eşliğinde</span><small class="muted">Anlat → Uygula → Ödev → Tekrar</small></div><h3>Bu dersten ne öğreneceksin?</h3><p>${h(teacherOneLine(l))}</p>${theory?`<div class="teacher-example"><strong>Öğretmen örneği</strong><p>${h(theory[1])}</p><small>${h(theory[2])}</small></div>`:''}<div class="row wrap"><button class="btn secondary" data-action="teacher-explain" ${tutorExplanationBusy?'disabled':''}>${tutorExplanationBusy?'AI anlatıyor…':'✦ AI farklı şekilde anlatsın'}</button><button class="btn secondary" data-action="teacher-open-homework">📝 Ödevime git</button></div>${tutorExplanationError?`<div class="warning">${h(tutorExplanationError)}</div>`:''}${exp?`<div class="teacher-answer"><strong>AI öğretmenin açıklaması</strong><p>${h(exp.text)}</p><button class="mini-tab" data-action="teacher-save-explain">☆ Ezberime kaydet</button></div>`:''}<div class="teacher-check"><strong>Öğretmenle soru-cevap</strong><p class="muted">Anladığın konuyu kendi cümlenle uygula. AI cevabını kontrol edip yeni bir soru soracak.</p>${state.tutorDialogs[l.id]?.lastAnswer?`<div class="teacher-answer"><strong>Son yazdığın:</strong><p>${h(state.tutorDialogs[l.id].lastAnswer)}</p><strong>Öğretmenin geri bildirimi:</strong><p>${h(state.tutorDialogs[l.id].lastReply||'')}</p></div>`:''}<textarea class="field" id="teacher-student-reply" rows="2" maxlength="450" placeholder="Konuyla ilgili İngilizce bir cümle yaz…">${h(state.tutorDialogs[l.id]?.draft||'')}</textarea><button class="btn secondary full" data-action="teacher-reply" ${tutorReplyBusy?'disabled':''}>${tutorReplyBusy?'Öğretmen kontrol ediyor…':'Cümlemi öğretmene kontrol ettir →'}</button>${tutorReplyError?`<div class="warning">${h(tutorReplyError)}</div>`:''}</div><p class="tiny">AI erişimi olmadığında ders notları ve hazır sınavlar kullanılabilir. AI açıklamaları hata içerebilir.</p></div>`}
function teacherHomeworkTasks(l){
 // Keep homework distinct from the lesson's four-question mini exam: practice with two recall items and one writing item.
 const qs=l.questions||[];let ordered=[qs.find(q=>q.type==='translate'),qs.find(q=>q.type==='fill'),qs.find(q=>q.type==='choice')].filter(Boolean);if(ordered.length<3)ordered=qs.slice(0,3);
 return [...ordered.slice(0,3).map((q,i)=>({key:'q'+i,type:q.type,title:q.q,options:q.options||[],answers:q.answers||[],why:q.why||''})),{key:'own',type:'own',title:`${l.title} konusuyla ilgili kendi hayatından bir İngilizce cümle yaz. Hazır örneği kopyalamak yerine yeni bir cümle kur.`,options:[],answers:[],why:''}];
}
function teacherHomeworkSummary(l){let a=teacherAssignment(l);let label=a.status==='completed'?'Tamamlandı':a.status==='reviewed'?'AI kontrol etti — yeniden çalış':a.status==='await_ai'?'AI değerlendirmesi bekliyor':a.status==='submitted'?'Kontrol edildi':'Yapılacak';return `${label}${a.score===null?'':' · %'+a.score}`;}
function renderHomework(){const l=LESSONS.find(x=>x.id===state.activeHomework)||currentLesson();state.activeHomework=l.id;const a=teacherAssignment(l),tasks=teacherHomeworkTasks(l),isFinished=a.status==='completed'||a.status==='reviewed';const due=new Date(a.dueAt).toLocaleDateString('tr-TR',{day:'numeric',month:'long'});
 root.innerHTML=`<div class="eyebrow">Teacher's homework</div><h1>Ödevlerim</h1><p class="muted">Öğretmenin alıştırmalarını yap, sonra cevaplarını kontrol ettir. Yanlışların sonraki ders planına yansır.</p><div class="card"><div class="row between"><span class="badge">${cap(l)}</span><span class="badge">${h(teacherHomeworkSummary(l))}</span></div><h3>${h(l.title)}</h3><p class="muted">Teslim hedefi: ${h(due)} · ${a.attempts} deneme</p>${tasks.map((q,i)=>`<div class="teacher-question"><strong>${i+1}. ${h(q.title)}</strong>${q.type==='choice'?`<div class="teacher-choices">${q.options.map(o=>`<label><input type="radio" name="hw-${q.key}" value="${h(o)}" ${a.answers[q.key]===o?'checked':''}><span>${h(o)}</span></label>`).join('')}</div>`:`<textarea class="field" data-hw-answer="${q.key}" rows="${q.type==='own'?3:2}" maxlength="${q.type==='own'?450:220}" placeholder="Cevabını yaz…">${h(a.answers[q.key]||'')}</textarea>`}${a.objective?.[i]&&a.status!=='assigned'&&a.status!=='draft'?`<div class="feedback ${a.objective[i].ok?'':'bad'}"><strong>${a.objective[i].ok?'✓ Doğru':'✕ Tekrar çalış'}</strong><p>${h(q.why)}</p>${a.objective[i].ok?'':`<p>Örnek doğru cevap: ${h(q.answers[0])}</p>`}</div>`:''}</div>`).join('')}${a.aiReview?`<div class="teacher-answer"><strong>AI öğretmenin yazılı ödev yorumu</strong><p>${h(a.aiReview.explanation)}</p><p><strong>Önerilen cümle:</strong> ${h(a.aiReview.corrected)}</p>${a.aiReview.suggestion?`<p><strong>Yeni alıştırma:</strong> ${h(a.aiReview.suggestion)}</p>`:''}<small>Yazı değerlendirmesidir; ses/telaffuz değerlendirmesi değildir.</small></div>`:''}${tutorHomeworkError?`<div class="warning">${h(tutorHomeworkError)}</div>`:''}<button class="btn full" data-action="teacher-submit-homework" ${tutorHomeworkBusy?'disabled':''}>${tutorHomeworkBusy?'AI ödevini kontrol ediyor…':isFinished?'Ödevi yeniden değerlendir':'📝 Ödevimi kontrol et'}</button>${a.status==='await_ai'?`<p class="tiny">Cevapların telefonda kaydedildi. Açık uçlu cümlenin kontrolü için Cloudflare AI bağlantısı gerekir; daha sonra tekrar deneyebilirsin.</p>`:''}</div><div class="card"><h3>Öğretmenin çalışma yöntemi</h3><p class="muted">1. Önce kendi başına cevapla. 2. Yanlışlarını açıklamayla öğren. 3. Yazılı cümleni AI'a kontrol ettir. 4. Eksikse konuyu tekrar et.</p><button class="btn secondary full" data-action="teacher-back-lesson">← Konu anlatımına dön</button></div><div class="card"><h3>Ödev geçmişi</h3>${Object.values(teacherStore()).filter(x=>x&&x.status==='completed').length?Object.values(state.homework).filter(x=>x&&x.status==='completed').slice(-6).map(x=>`<p class="muted">${h(LESSONS.find(l=>l.id===x.lessonId)?.title||x.lessonId)} · %${Number(x.score)||0}</p>`).join(''):'<p class="muted">Henüz tamamlanan ödev yok.</p>'}</div>`;
}
function teacherInputUpdate(el){const l=LESSONS.find(x=>x.id===state.activeHomework)||currentLesson(),a=teacherAssignment(l);const key=el.dataset.hwAnswer||el.name?.replace(/^hw-/,'');if(!key)return;a.answers[key]=el.value; if(a.status!=='assigned'&&a.status!=='draft'){a.status='draft';a.aiReview=null;a.score=null;a.objective=[];delete a.lastSubmission;}save();}
function teacherRecordMistake(l,q,index){const key='homework_'+l.id+'_'+index,m=state.misses[key];state.misses[key]={interval:0,due:Date.now()+86400000,errors:(m?.errors||0)+1,title:q.title,answer:q.answers[0]};}
function teacherMarkPlan(l){const plan=dailyPlan();if(plan.lessonId===l.id){plan.steps.homework=true;save();}}
async function teacherSubmitHomework(){if(tutorHomeworkBusy)return;const l=LESSONS.find(x=>x.id===state.activeHomework)||currentLesson(),a=teacherAssignment(l),tasks=teacherHomeworkTasks(l);tutorHomeworkError='';
 for(const task of tasks){if(!String(a.answers[task.key]||'').trim()){tutorHomeworkError='Dört sorunun tamamını cevapla. Cevapların otomatik kaydediliyor.';renderHomework();return;}}
 const submission=JSON.stringify(a.answers);if(a.lastSubmission!==submission){a.attempts++;a.submittedAt=Date.now();a.objective=tasks.slice(0,3).map((q,i)=>({ok:answered(q,a.answers[q.key]),why:q.why}));a.lastSubmission=submission;for(let i=0;i<3;i++)if(!a.objective[i].ok)teacherRecordMistake(l,tasks[i],i);}
 a.status='await_ai';a.aiReview=null;const fixed=a.objective.filter(q=>q.ok).length;save();
 if(state.settings.ai!=='cloud'||!workerAddressValid(state.settings.worker)||!state.settings.token){tutorHomeworkError=`Hazır sorular: ${fixed}/3 doğru. Kendi cümlenin AI değerlendirmesi için Ayarlar'dan gerçek AI bağlantısını kullan. Ödevin kaydedildi.`;renderHomework();return;}
 tutorHomeworkBusy=true;renderHomework();try{
  const body={action:'evaluate_homework',lesson:{level:l.level,title:l.title,rule:l.rule},prompt:tasks[3].title,answer:a.answers.own};
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),55000);let res;
  try{res=await fetch(state.settings.worker,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.token},body:JSON.stringify(body),signal:controller.signal});}finally{clearTimeout(timer)}
  const data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error||('HTTP '+res.status));if(!data.review||typeof data.review.correct!=='boolean')throw Error('AI değerlendirmesi geçerli biçimde gelmedi.');
  a.aiReview={correct:data.review.correct,explanation:String(data.review.explanation||'').slice(0,650),corrected:String(data.review.corrected||'').slice(0,400),suggestion:String(data.review.suggestion||'').slice(0,300)};
  a.score=Math.round((fixed+Number(a.aiReview.correct))/4*100);a.status=a.score>=75?'completed':'reviewed';if(a.status==='completed')teacherMarkPlan(l);else state.tutorHistory.push({lessonId:l.id,at:Date.now(),kind:'homework-review',note:'Ödeve yeniden çalış: '+l.title});state.tutorHistory=state.tutorHistory.slice(-80);activity();save();
 }catch(e){tutorHomeworkError='Hazır sorular kontrol edildi. AI açık uçlu cevabına henüz bakamadı: '+String(e.message||e).slice(0,180)+' — tekrar deneyebilirsin.';a.status='await_ai';save();}finally{tutorHomeworkBusy=false;renderHomework();}
}
async function teacherExplain(){if(tutorExplanationBusy)return;const l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();if(state.settings.ai!=='cloud'||!workerAddressValid(state.settings.worker)||!state.settings.token){tutorExplanationError='AI ile ayrıntılı anlatım için Ayarlar bölümünde Cloudflare AI bağlantısını aç. Mevcut konu anlatımı çevrimdışı kullanılabilir.';renderLesson();return;}
 tutorExplanationBusy=true;tutorExplanationError='';renderLesson();try{
  const user=`Öğrencinin konusu: ${l.title}. Kural: ${l.rule}. Adım adım Türkçe anlat, 3 günlük hayat örneği ver, en sık 2 yanlışı açıkla, sonuna tek küçük düşünme sorusu koy. Cevabı doğrudan verme.`;
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000);let response;
  try{response=await fetch(state.settings.worker,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.token},body:JSON.stringify({messages:[{role:'user',content:user}],context:{mode:'lesson',level:l.level,title:l.title,rule:l.rule,mistakes:Object.values(state.misses).slice(-5).map(m=>m.title)}}),signal:controller.signal});}finally{clearTimeout(timer)}
  const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||('HTTP '+response.status));if(!data.reply)throw Error('AI boş cevap döndürdü.');teacherStore();state.tutorExplanations[l.id]={text:String(data.reply).slice(0,2200),at:Date.now()};dailyPlan().steps.explain=true;activity();save();
 }catch(e){tutorExplanationError='AI açıklaması alınamadı: '+String(e.message||e).slice(0,160);}finally{tutorExplanationBusy=false;if(page==='lesson')renderLesson();}
}
function teacherDraftUpdate(value){const l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();teacherStore();const dialog=state.tutorDialogs[l.id]||{draft:'',lastAnswer:'',lastReply:'',turns:0};dialog.draft=String(value||'').slice(0,450);state.tutorDialogs[l.id]=dialog;save();}
async function teacherReply(){if(tutorReplyBusy)return;const l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();teacherStore();let d=state.tutorDialogs[l.id]||{draft:''};const answer=String(d.draft||'').trim();tutorReplyError='';if(!answer){tutorReplyError='Önce İngilizce bir cümle yaz.';renderLesson();return;}
 if(state.settings.ai!=='cloud'||!workerAddressValid(state.settings.worker)||!state.settings.token){tutorReplyError='Cümlen kaydedildi. Kişisel geri bildirim için Cloudflare AI bağlantısını etkinleştir.';renderLesson();return;}
 tutorReplyBusy=true;renderLesson();try{
  const prior=state.tutorExplanations[l.id]?.text||teacherOneLine(l);
  const prev=d.lastReply||prior;
  const messages=[{role:'assistant',content:String(prev).slice(-1100)},{role:'user',content:`Öğretmenim, benim yazdığım İngilizce cümle: ${answer}. Bunu konumuz '${l.title}' açısından kontrol et. Doğruysa doğru olduğunu belirt; yanlışsa doğal düzeltmesini Türkçe açıkla. Sonuna bir sonraki kısa İngilizce uygulama sorusunu ekle.`}];
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),55000);let res;
  try{res=await fetch(state.settings.worker,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+state.settings.token},body:JSON.stringify({messages,context:{mode:'feedback',level:l.level,title:l.title,rule:l.rule}}),signal:controller.signal});}finally{clearTimeout(timer)}
  let data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error||('HTTP '+res.status));if(!String(data.reply||'').trim())throw Error('AI yanıtı boş.');
  d.lastAnswer=answer;d.lastReply=String(data.reply).slice(0,2200);d.draft='';d.turns=Math.min(999,Number(d.turns||0)+1);d.updated=Date.now();state.tutorDialogs[l.id]=d;activity();save();
 }catch(e){tutorReplyError='Öğretmenden cevap alınamadı; yazdığın cümle saklandı: '+String(e.message||e).slice(0,150);}finally{tutorReplyBusy=false;if(page==='lesson')renderLesson();}
}
function teacherMaybeAutoExplain(){const l=LESSONS.find(x=>x.id===state.activeLesson)||currentLesson();if(state.settings.ai!=='cloud'||!workerAddressValid(state.settings.worker)||!state.settings.token)return;teacherStore();if(state.tutorExplanations[l.id]||tutorAutoTried.has(l.id)||tutorExplanationBusy)return;tutorAutoTried.add(l.id);Promise.resolve().then(()=>{if(page==='lesson'&&state.activeLesson===l.id)teacherExplain();});}
function teacherOpenHomework(){const l=page==='lesson'?(LESSONS.find(x=>x.id===state.activeLesson)||currentLesson()):currentLesson();state.activeHomework=l.id;teacherAssignment(l);save();go('homework');}
function teacherHomeworkStats(){teacherStore();return {total:Object.keys(state.homework).length,done:Object.values(state.homework).filter(x=>x?.status==='completed').length,pending:teacherPendingAssignments().length};}
